/** Dicionários PT / EN — chaves estáveis para i18n. */

export const TRADUCOES = {
  pt: {
    "app.title": "North",
    "header.brand": "North",
    "header.tagline": "Te dá direção — corpo, mente e conhecimento, sem peso na cabeça.",
    "header.day": "North",
    "nav.north": "North",
    "nav.memoria": "Memória",
    "nav.hoje": "Agora",
    "nav.guia": "Guia",
    "nav.estudo": "Conhecimento",
    "nav.rotina": "Ritmo",
    "nav.semana": "Direção",
    "nav.diario": "Diário",
    "nav.insights": "Continuidade",
    "nav.ajustes": "Ajustes",
    "nav.aria": "Áreas do North",
    "panel.hoje": "North",
    "panel.memoria": "Memória",
    "panel.guia": "Guia",
    "panel.cheguei": "E agora?",
    "panel.estudo": "Conhecimento",
    "panel.rotina": "Ritmo",
    "panel.semana": "Direção",
    "panel.diario": "Diário",
    "panel.insights": "Continuidade",
    "panel.ajustes": "Ajustes",
    "panel.default": "North",
    "theme.aria": "Alternar tema",
    "guia.chamada.html":
      "<strong>Primeira vez?</strong> O <strong>Guia</strong> mostra como o North te dá direção em 5 min.",
    "guia.chamada.abrir": "Abrir Guia",
    "guia.chamada.depois": "Depois",
    "dica.inicio.html":
      "<strong>Hoje</strong> mostra um foco só. O resto já está organizado por baixo.",
    "dica.entendi": "Entendi",
    "hoje.manha.titulo": "Manhã — 2 min",
    "hoje.manha.apoio": "O que importa hoje? Três linhas no máximo.",
    "hoje.prioridade": "O que importa {{n}}",
    "hoje.prioridade1": "O que importa 1",
    "hoje.prioridade2": "O que importa 2",
    "hoje.prioridade3": "O que importa 3",
    "hoje.tema": "Tema da semana",
    "hoje.tema.placeholder": "Ex.: Corpo, mente e conhecimento",
    "hoje.agora": "Agora",
    "hoje.inbox.titulo": "Captura — fora da cabeça",
    "hoje.inbox.apoio": "Qualquer pensamento em 10 segundos. O North guarda — sem pressão.",
    "hoje.inbox.placeholder": "Ex.: ligar pro médico, ideia do trabalho...",
    "hoje.inbox.anotar": "Anotar",
    "hoje.inbox.vazio": "Nada na inbox. Quando surgir algo, jogue aqui.",
    "hoje.inbox.arquivar": "Guardar tudo e limpar a cabeça",
    "hoje.avisos.titulo": "Avisos",
    "hoje.avisos.apoio":
      "Lembretes com data e hora — como no calendário. Ative notificações em <strong>Ajustes</strong>.",
    "hoje.avisos.placeholder": "Ex.: Entregar trabalho, consulta médica...",
    "hoje.avisos.adicionar": "Adicionar aviso",
    "hoje.avisos.vazio": "Nenhum aviso para hoje.",
    "hoje.compromissos": "Passos de hoje",
    "hoje.ritmo": "Ritmo da semana",
    "hoje.revisao.titulo": "Revisão do dia — 2 min",
    "hoje.revisao.apoio": "O que ficou? O que amanhã? Sem julgamento.",
    "hoje.nota.titulo": "Anotações do dia",
    "hoje.nota.placeholder": "Livre — humor, ideias, o que quiser lembrar.",
    "agora.link.cheguei": "E agora? — só 2 opções",
    "agora.dica": "Um passo só. Sem precisar fazer tudo.",
    "agora.vazio": "Nada pendente agora. Descanse ou revise a inbox.",
    "agora.mais": "Mais opções",
    "agora.travei": "Travei",
    "agora.cronometro": "Cronômetro",
    "agora.parar": "Parar",
    "agora.travei.titulo": "Travou? Plano B — só o mínimo",
    "agora.travei.30s": "Só 30 segundos",
    "agora.travei.ok": "Ok, entendi",
    "cheguei.voltar": "← Voltar ao Guia",
    "cheguei.ola": "E agora?",
    "cheguei.apoio": "Sem lista enorme — diga o que acabou de acontecer e eu monto 2 opções.",
    "cheguei.apoio.madrugada": "É madrugada — nada de trabalho pesado. Diga o que acabou de acontecer:",
    "cheguei.voz": "Falar — eu entendo",
    "cheguei.ou.voz": "ou escolha:",
    "cheguei.ou": "ou",
    "cheguei.reiniciar": "Outra situação",
    "cheguei.feito.titulo": "Boa.",
    "cheguei.feito.mais": "Ver mais 2 opções",
    "cheguei.ia": "✨ ajustado pela IA",
    "cheguei.gatilho.chegada": "Cheguei em casa",
    "cheguei.gatilho.tarefa": "Terminei algo",
    "cheguei.gatilho.acordar": "Acabei de acordar",
    "cheguei.gatilho.pausa": "Preciso de uma pausa",
    "cheguei.gatilho.noite": "Vou desacelerar",
    "guia.hero.kicker": "North · v{{versao}}",
    "guia.hero.titulo": "Um passo de cada vez",
    "guia.hero.apoio":
      "{{nome}}, {{faixa}} · {{hora}}. Sou o North — te dou direção sem peso na cabeça.",
    "guia.demo.iniciar": "▶ Iniciar roteiro de 5 min",
    "guia.cheguei.btn": "E agora? — 2 opções",
    "guia.progresso": "Roteiro de demonstração",
    "guia.reset": "Zerar progresso do roteiro",
    "guia.mapa.titulo": "Mapa das abas",
    "guia.mapa.apoio": "Referência rápida — use só se precisar.",
    "guia.dicas.titulo": "Referência extra",
    "guia.ia.ativa": "✨ IA ativa no servidor — Neuro, Diário e Agora podem usar inteligência.",
    "guia.ia.local":
      "⚠️ IA offline — configure GROQ_API_KEY no Vercel para Neuro, Diário e Cheguei.",
    "guia.demo.banner": "Modo apresentação — passo <strong>{{atual}}</strong> de {{total}}",
    "guia.demo.proximo": "Próximo passo →",
    "guia.demo.sair": "Sair do modo",
    "guia.passo.abrir": "Abrir e mostrar →",
    "guia.passo.feito": "✓ Feito",
    "guia.passo.marcar": "Marcar como feito",
    "guia.passo.falar": "<strong>O que dizer:</strong> {{texto}}",
    "guia.tempo.30s": "30 s",
    "guia.tempo.1min": "1 min",
    "guia.tempo.2min": "2 min",
    "guia.rota.hoje.titulo": "Hoje — um foco",
    "guia.rota.hoje.falar":
      "Saudação, um passo, o que vem depois. Sem lista enorme — só direção.",
    "guia.rota.cheguei.titulo": "E agora? — só 2 opções",
    "guia.rota.cheguei.falar":
      "Quando a cabeça trava, o app oferece no máximo duas escolhas contextuais — sem lista infinita.",
    "guia.rota.neuro.titulo": "Estudo → Neuro",
    "guia.rota.neuro.falar":
      "Trilha de neurociência: ler, explicar com voz ou texto e receber feedback. Módulo TDAH impressiona.",
    "guia.rota.diario.titulo": "Diário com IA",
    "guia.rota.diario.falar":
      "Anotações do dia ficam seguras. Toque em Organizar com IA para um resumo gentil.",
    "guia.rota.insights.titulo": "Insights — continuidade",
    "guia.rota.insights.falar": "Sem culpa: o app mostra continuidade, não cobrança.",
    "guia.ref.hoje": "Um foco, depois disso, alívio.",
    "guia.ref.estudo": "Conhecimento — vídeo, neuro, prática.",
    "guia.ref.rotina": "Ritmo do dia — ajustes recolhidos.",
    "guia.ref.semana": "Direção da semana — números opcionais.",
    "guia.ref.diario": "Anotações seguras, com histórico.",
    "guia.ref.insights": "Continuidade gentil — detalhes recolhidos.",
    "guia.ref.ajustes": "Nome, horários, sync e idioma.",
    "guia.mais.referencia": "Referência completa",
    "guia.dica.1": "Use Chrome ou Safari no celular — voz e instalação na tela inicial funcionam melhor.",
    "guia.dica.2": "Permita o microfone na primeira vez (Estudo → Neuro → Explicar só com voz).",
    "guia.dica.3": "Se algo parecer antigo, segure o botão de recarregar para atualizar a versão.",
    "guia.dica.4": "O app funciona offline; IA (quando configurada) precisa de internet no Vercel.",
    "guia.dica.5": "Para impressionar: comece pelo roteiro abaixo — leva cerca de 5 minutos.",
    "offline.banner":
      "Sem internet — seus dados estão salvos neste aparelho. IA e sync voltam quando conectar.",
    "faixa.manha": "manhã",
    "faixa.tarde": "tarde",
    "faixa.noite": "noite",
    "faixa.madrugada": "madrugada",
    "ajustes.idioma.titulo": "Idioma",
    "ajustes.idioma.apoio": "Por enquanto: português e inglês. O app lembra sua escolha.",
    "ajustes.idioma.pt": "Português",
    "ajustes.idioma.en": "English",
    "ajustes.rotina.titulo": "Seu ritmo",
    "ajustes.rotina.apoio":
      "Ajuste seus horários — o ritmo recalcula estudo, água e sono automaticamente.",
    "ajustes.rotina.acordar": "Acordar",
    "ajustes.rotina.dormir": "Dormir",
    "ajustes.rotina.chegada": "Chego em casa",
    "ajustes.rotina.tardeFim": "Fim da tarde difícil",
    "ajustes.rotina.praia": "Trabalho na praia no fim de semana",
    "ajustes.rotina.preview": "Prévia do ritmo",
    "ajustes.rotina.botao": "Recalcular meu ritmo",
    "ajustes.rotina.confirmar":
      "Vai atualizar {{total}} passos do ritmo (estudo às {{estudo}}). Os seus personalizados ficam. Continuar?",
    "ajustes.rotina.ok": "Ritmo recalculado! {{novos}} novo(s), {{atualizados}} atualizado(s). Veja em Agora.",
    "ajustes.rotina.erro": "Não foi possível recalcular o ritmo. Tente de novo.",
    "ajustes.rotina.perfil": "Acorda {{acordar}}, escola seg–sex, tarde difícil {{tardeIni}}–{{tardeFim}}. O que importa: {{prioridades}}.",
    "ajustes.sobre.titulo": "Sobre",
    "ajustes.sobre.apoio":
      "Te dá direção — corpo, mente e conhecimento, sem peso na cabeça. Use pouco. Use todo dia.",
    "ajustes.atualizar": "Buscar atualização",
    "feedback.idioma": "Idioma alterado.",
    "feedback.guia.reset": "Progresso do roteiro zerado.",
    "feedback.demo.fim": "Roteiro completo! Você arrasou na demonstração.",
    "feedback.demo.passo": "Demonstração — {{titulo}}",
    "rotina.adicionar.titulo": "Incluir no ritmo",
    "rotina.adicionar.apoio": "Toque num atalho ou escreva. No Agora, só o próximo passo aparece.",
    "rotina.adicionar.placeholder": "O que quer lembrar no dia?",
    "rotina.adicionar.btn": "Adicionar",
    "rotina.opcoes.summary": "Horário e importância (opcional)",
    "rotina.atalho.agua": "💧 Água",
    "rotina.atalho.academia": "🏋️ Academia",
    "rotina.atalho.estudo": "🎧 Aprender",
    "rotina.atalho.vocabulario": "🗣️ Vocabulário",
    "rotina.atalho.praticalivro": "📖 Prática",
    "rotina.atalho.meditar": "🧘 Meditar",
    "rotina.sugestao.usar": "Usar sugestão",
    "rotina.importancia.1": "Essencial",
    "rotina.importancia.2": "Importante",
    "rotina.importancia.3": "Normal",
    "diario.titulo": "Diário",
    "diario.apoio": "Escreva livremente. Toque em Organizar com IA para um resumo gentil.",
    "diario.apoio.html":
      "Cada dia guarda uma entrada. É o <strong>mesmo texto</strong> de <strong>Hoje → Anotações do dia</strong>. Salva sozinho a cada alteração — <strong>uma versão nova a cada salvamento</strong> fica em <strong>Histórico</strong>.",
    "diario.data": "Data",
    "diario.placeholder": "Escreva sobre este dia…",
    "diario.hoje": "Ir para hoje",
    "diario.ontem": "Ver ontem",
    "diario.salvar": "Salvar entrada",
    "diario.resumo.ia": "Organizar com IA",
    "diario.historico": "Histórico",
    "diario.historico.apoio": "Até 2 versões por dia — só quando o texto muda. Toque para restaurar.",
    "diario.historico.vazio":
      "Ainda sem versões guardadas para esta data. Escreva um pouco — o app salva automaticamente.",
    "diario.busca.titulo": "Busca de texto antigo",
    "diario.busca.apoio": "Vasculha o histórico e todo o navegador por textos longos que possam ter sumido.",
    "diario.busca.btn": "Procurar agora",
    "diario.busca.vazio": "Nenhum resultado ainda. Toque em <strong>Procurar agora</strong>.",
    "diario.entradas": "Entradas salvas",
    "diario.entradas.apoio": "Toque numa data para abrir aquela nota.",
    "diario.vazio":
      "Nenhuma entrada ainda. Escreva na aba Hoje ou aqui — elas aparecem automaticamente. Se você escreveu ontem e sumiu, toque em <strong>Ver ontem</strong> ou use <strong>Restaurar anotações</strong> se aparecer acima.",
    "semana.grafico": "Últimos 7 dias",
    "semana.grafico.apoio": "Quanto do ritmo você manteve em cada dia.",
    "semana.metas": "Ritmo da semana",
    "semana.metas.apoio": "Quanto do ritmo você manteve — sem cobrança.",
    "semana.resumo": "Resumo",
    "semana.resumo.titulo": "Resumo da semana",
    "semana.resumo.apoio": "Uma leitura do seu último ciclo de 7 dias.",
    "semana.plano.ia": "Direção sugerida da semana",
    "insights.mes": "Este mês — continuidade",
    "insights.mes.apoio": "Intensidade = quanto do seu ritmo você manteve no dia.",
    "sync.titulo": "Sincronizar Mac e iPhone",
    "sync.apoio": "Mesmo código em todos os aparelhos — seus dados ficam iguais.",
    "sync.criar": "Criar sincronização",
    "sync.codigo": "Código:",
    "sync.placeholder": "Código do outro aparelho",
    "sync.carregando": "Carregando…",
    "sync.apoio.html":
      "Crie um código neste aparelho e digite o mesmo código no outro. Assim ritmo, diário e trilha Neuro ficam iguais — inclusive ao trocar de endereço (GitHub → Vercel).",
    "sync.entrar": "Entrar com código",
    "sync.copiar": "Copiar código",
    "sync.desconectar": "Desconectar",
    "lembretes.titulo": "Avisos do North",
    "lembretes.apoio": "Avisos do North — funciona melhor no iPhone instalado na tela inicial.",
    "lembretes.apoio.html":
      "Instale o app na tela inicial para receber avisos mesmo com o navegador fechado. Abra o menu do navegador → <strong>Adicionar à tela inicial</strong>.",
    "lembretes.btn": "Ativar lembretes",
    "vercel.titulo": "App principal (Vercel)",
    "vercel.apoio": "URL recomendada no iPhone e no Mac — app completo + IA + deploy automático a cada git push:",
    "vercel.apoio.html":
      "URL recomendada no iPhone e no Mac — app completo + IA + deploy automático a cada <code>git push</code>: <a href=\"https://projeto-1-criar.vercel.app\" target=\"_blank\" rel=\"noopener noreferrer\">projeto-1-criar.vercel.app</a>",
    "vercel.dica": "Use o <strong>mesmo código de sync</strong> em todos os aparelhos. IA via <strong>Groq</strong> no Vercel — sem fallback local.",
    "backup.titulo": "Backup dos dados",
    "backup.apoio": "Mesmo com sync, exporte de vez em quando. O backup é uma cópia de segurança extra.",
    "backup.exportar": "Exportar",
    "backup.importar": "Importar",
    "hoje.nota.salvar": "Salvar anotações",
    "migracao.github.texto": "Para IA completa e sync, use a versão no Vercel:",
    "migracao.github.html":
      "Nova versão com IA: <a data-migracao-link-vercel href=\"https://projeto-1-criar.vercel.app\">projeto-1-criar.vercel.app</a> — use o <strong>mesmo código de sync</strong>.",
    "migracao.github.ir": "Abrir no Vercel",
    "migracao.host.titulo": "Restaurar seus dados",
    "migracao.host.texto": "Este aparelho ainda não tem seu código de sync. Conecte em Ajustes para trazer diário e ritmo.",
    "migracao.host.texto.html":
      "Este endereço é novo neste aparelho. Seu <strong>diário</strong>, ritmo e trilha Neuro estão seguros na <strong>sincronização</strong> — entre com o mesmo código que você já usa no celular.",
    "migracao.host.alerta":
      "⚠️ Antes de escrever no diário aqui, conecte o sync para não sobrescrever a nuvem com texto vazio.",
    "migracao.host.ajustes": "Ir para Ajustes → Sync",
    "migracao.host.exportar": "Exportar backup",
    "rotina.adicionar.apoio.html": "Toque num atalho ou escreva. No <strong>Agora</strong>, só o próximo passo aparece.",
    "hoje.nota.apoio.html":
      "O que marcou este dia? O histórico fica na aba <strong>Diário</strong> — é a mesma entrada de hoje.",
    "neuro.titulo": "Neuro — aprender explicando",
    "neuro.fase": "Fase D",
    "neuro.trilha.apoio": "Trilha com {{total}} módulos · leia → explique (voz ou texto) → feedback{{ia}}. Hoje: {{hoje}}/{{total}}.",
    "neuro.trilha.ia": " com IA",
    "neuro.pontos": "Pontos-chave",
    "neuro.explicar.dica": "Como se estivesse ensinando uma amiga — voz ou texto.",
    "neuro.placeholder": "Escreva ou use o microfone acima...",
    "neuro.verificar.ia": "Verificar com IA ✨",
    "neuro.verificar.local": "Verificar minha explicação",
    "neuro.proximo": "Próximo: {{titulo}} →",
    "neuro.timer": "Timer 10 min",
    "neuro.voz.completa": "🎤 Explicar só com voz",
    "neuro.voz.dictado": "🎤 Acrescentar por voz",
    "neuro.voz.indisponivel": "Microfone indisponível — escreva abaixo.",
    "neuro.ia.carregando": "✨ A IA está lendo sua explicação…",
    "neuro.fb.fonte": "Correção com IA ✨",
    "neuro.fb.pct": "{{pct}}% do essencial",
    "neuro.fb.acertos": "Você mencionou:",
    "neuro.fb.faltou": "Ainda vale incluir:",
    "neuro.fb.pergunta": "Pra pensar:",
    "neuro.fb.ouvir": "🔊 Ouvir feedback",
    "neuro.fb.responder": "🎤 Responder pergunta",
    "common.fechar": "Fechar",
    "sync.aviso.firebase.html":
      "Ainda falta configurar o Firebase (é grátis). Peça ao assistente o passo a passo ou cole a config em <code>firebase-config.js</code>.",
    "sync.status.firebase": "Firebase ainda não configurado.",
    "sync.status.ativo": "Sincronização ativa neste aparelho.",
    "sync.status.sem": "Sem sincronização. Crie um código ou entre com um existente.",
    "sync.status.sincronizado": "Sincronizado agora.",
    "sync.status.falha_envio": "Falha ao enviar para a nuvem. Tente de novo.",
    "sync.status.atualizado_nuvem": "Atualizado da nuvem.",
    "sync.status.erro_ouvir": "Erro ao ouvir a nuvem.",
    "sync.status.codigo_invalido": "Código inválido. Use pelo menos 6 caracteres.",
    "sync.status.codigo_nao_encontrado": "Código não encontrado. Confira ou crie uma sincronização nova.",
    "sync.status.criado": "Sincronização criada. Use este código no outro aparelho.",
    "sync.status.conectado": "Conectado. Dados sincronizados.",
    "sync.status.desconectado": "Sincronização desligada neste aparelho. Os dados locais continuam aqui.",
    "sync.status.copiado": "Código copiado. Cole no outro aparelho.",
    "sync.status.copia_falha": "Não deu para copiar. Anote o código: {{codigo}}",
    "sync.status.erro_criar": "Erro ao criar sincronização.",
    "sync.status.erro_conectar": "Erro ao conectar.",
    "sync.status.firebase_lib": "Biblioteca Firebase não carregou.",
    "sync.status.firebase_init": "Não foi possível iniciar o Firebase. Confira a configuração.",
    "lembretes.status.indisponivel": "Notificações não disponíveis neste navegador.",
    "lembretes.status.ativo": "Lembretes ativos — avisos no horário (melhor com app na tela inicial).",
    "lembretes.status.bloqueado": "Permissão bloqueada. Libere nas configurações do navegador.",
    "lembretes.status.off": "Lembretes desligados.",
    "lembretes.perm.indisponivel": "Este navegador não suporta notificações.",
    "lembretes.perm.ativado": "Lembretes ativados.",
    "lembretes.perm.negado": "Permissão negada. Ative nas configurações do navegador.",
    "lembretes.perm.nao_concedida": "Permissão não concedida.",
    "insights.card.sequencia": "Continuidade",
    "insights.card.hoje": "Hoje",
    "insights.card.30dias": "30 dias",
    "insights.card.recorde": "Recorde",
    "insights.card.compromissos": "passos dados hoje",
    "insights.card.taxa": "ritmo mantido",
    "insights.card.melhor": "melhor continuidade",
    "streak.global.0": "Hoje é um novo começo — um passo já conta.",
    "streak.global.1": "1 dia seguido. Sem pressão pra manter — só celebre.",
    "streak.global.curto": "{{n}} dias seguidos. Você tá construindo ritmo.",
    "streak.global.medio": "{{n}} dias! Isso é consistência de verdade.",
    "streak.global.longo": "{{n}} dias seguidos — impressionante, mas descanse se precisar.",
    "streak.habito.voltou": "Voltou depois de {{n}} dias — isso também conta.",
    "streak.habito.1": "1 dia — começo leve.",
    "streak.habito.recorde": "Recorde! {{n}} dias seguidos.",
    "streak.habito.normal": "{{n}} dias seguidos",
    "streak.rotulo.0": "Recomeço",
    "streak.rotulo.1": "dia seguido",
    "streak.rotulo.n": "dias seguidos",
    "diario.salvando": "Salvando…",
    "diario.salvo": "Salvo às {{hora}} · {{n}} caracteres",
    "diario.historico.meta": "{{hora}} · {{n}} caracteres · {{motivo}}",
    "diario.motivo.manual": "salvo por você",
    "diario.motivo.apagar": "antes de apagar",
    "diario.motivo.fechar": "ao sair",
    "diario.motivo.auto": "automático",
    "ajustes.sobre.versao.html": "Se a versão não mudar sozinha, toque em <strong>Buscar atualização</strong> abaixo.",
    "ajustes.versao": "Versão {{v}}{{host}}",
    "ajustes.buscando": "Buscando atualização…",
    "rotina.dias.todo": "todo dia",
    "rotina.dias.segsex": "seg–sex",
    "rotina.dias.sabdom": "sáb–dom",
    "rotina.dias.nxsem": "{{n}}x/sem",
    "rotina.preset.agua": "Beber água",
    "rotina.preset.organizar": "Organizar ao chegar (10 min)",
    "rotina.preset.aprender": "Aprender 15 min",
    "rotina.preset.praticalivro": "Prática do livro (10 min)",
    "rotina.preset.vocabulario": "Vocabulário 5 min",
    "rotina.preset.academia": "Academia",
    "rotina.preset.telas": "Desligar telas",
    "rotina.preset.sono": "Dormir no horário",
    "rotina.preset.manha": "Planejar o dia (2 min)",
    "rotina.preset.praia": "Preparar trabalho na praia",
    "mindos.saudacao.manha": "Bom dia",
    "mindos.saudacao.tarde": "Boa tarde",
    "mindos.saudacao.noite": "Boa noite",
    "mindos.ola.nome": "{{saudacao}}, {{nome}}.",
    "north.convite.estudo": "Vamos continuar nos estudos hoje?",
    "north.convite.diario": "Quer escrever um pouco?",
    "north.convite.manha": "Como quer começar o dia?",
    "north.convite.calmo": "Só um passo de cada vez — pronto quando você estiver.",
    "north.slogan": "Less to Think. More to Do.",
    "north.pergunta": "Como você está hoje?",
    "north.estado.aria": "Como você está hoje",
    "north.estado.sobrecarregado": "Sobrecarregado",
    "north.estado.sobrecarregado.emoji": "😵",
    "north.estado.normal": "Normal",
    "north.estado.normal.emoji": "😐",
    "north.estado.bem": "Bem",
    "north.estado.bem.emoji": "🙂",
    "north.estado.focado": "Focado",
    "north.estado.focado.emoji": "🔥",
    "north.transicao": "Então vamos por aqui.",
    "north.foco.rotulo": "Seu próximo passo",
    "north.foco.aprender": "Aprender",
    "north.foco.corpo": "Corpo",
    "north.foco.agora": "Agora",
    "north.foco.ingles": "Inglês",
    "north.foco.duracao": "{{n}} minutos",
    "north.foco.desc.aprender": "Desenvolver compreensão e conversação.",
    "north.foco.desc.corpo": "Mover o corpo com intenção.",
    "north.foco.desc.geral": "Um passo de cada vez — sem precisar pensar em tudo.",
    "north.comecar": "Começar →",
    "north.depois": "Em seguida",
    "north.estado.trocar": "Trocar estado",
    "north.livre": "Nada urgente agora. Respire.",
    "north.feito": "Feito.",
    "north.feito.apoio": "Você avançou hoje.",
    "north.feito.proximo": "Próximo passo preparado.",
    "north.continuar": "Continuar →",
    "north.encerrar": "Encerrar →",
    "north.foco.modo": "Foco",
    "north.finalizar": "Finalizar",
    "north.pausar": "Pausar",
    "north.retomar": "Retomar",
    "north.memoria.titulo": "Memória",
    "north.memoria.apoio": "Consultar — não agir. Tudo que importa, guardado.",
    "north.memoria.conhecimento": "Conhecimento",
    "north.memoria.conhecimento.apoio": "Estudo, trilhas e sessões cognitivas.",
    "north.memoria.diario": "Diário",
    "north.memoria.diario.apoio": "Registros, reflexões e histórico.",
    "north.memoria.direcao": "Direção",
    "north.memoria.direcao.apoio": "Semana, prioridades e plano.",
    "north.memoria.continuidade": "Continuidade",
    "north.memoria.continuidade.apoio": "Padrões, insights e progresso.",
    "north.memoria.ritmo": "Ritmo",
    "north.memoria.ritmo.apoio": "Mapa do dia e hábitos — ajustar quando quiser.",
    "mindos.sono": "Sono da rotina: {{duracao}}.",
    "mindos.foco.rotulo": "Hoje o foco é:",
    "mindos.comecar": "Começar",
    "mindos.depois.titulo": "Depois disso",
    "mindos.duracao.min": "{{n}} minutos",
    "mindos.rodape": "Sua mente está livre. O resto já está organizado.",
    "mindos.livre.tudo": "Nada urgente agora. Pode respirar.",
    "mindos.rodape.leve": "Só isso por agora. O resto pode esperar.",
    "mindos.rodape.minimo": "Um passo de cada vez.",
    "mindos.estado.aria": "Como está a cabeça hoje",
    "mindos.estado.pergunta": "Como está a cabeça?",
    "mindos.estado.melhor": "Estou melhor",
    "mindos.estado.organizado": "Organizado",
    "mindos.estado.motivado": "Motivado",
    "mindos.estado.distraido": "Distraído",
    "mindos.estado.ansioso": "Ansioso",
    "mindos.estado.cansado": "Cansado",
    "mindos.estado.sobrecarregado": "Sobrecarregado",
    "hoje.mais": "Ferramentas do dia",
    "hoje.mapa.mais": "Mapa do ritmo",
    "mindos.rotina.titulo": "Ritmo de hoje",
    "mindos.rotina.apoio": "O mapa do dia — sem precisar pensar em tudo.",
    "mindos.rotina.vazio": "Nada programado para hoje. Respire.",
    "mindos.rotina.rodape": "Ajuste o mapa abaixo. No Agora, só o próximo passo.",
    "mindos.rotina.mais": "Ajustar o mapa do dia",
    "mindos.semana.titulo": "Direção da semana",
    "mindos.semana.tema.placeholder": "Corpo, mente e conhecimento",
    "mindos.semana.progresso": "{{feitos}} passos dados esta semana — sem cobrança.",
    "mindos.semana.foco": "Foco agora:",
    "mindos.semana.rodape": "Os números ficam em segundo plano. O importante é a direção.",
    "mindos.semana.mais": "Ver números da semana",
    "mindos.insights.titulo": "Continuidade",
    "mindos.insights.default": "Cada retorno conta. A direção continua.",
    "mindos.insights.passos": "{{n}} passos esta semana — sem cobrança.",
    "mindos.insights.sem.passos": "Sem pressa. Um passo já basta.",
    "mindos.insights.rodape": "Números ficam recolhidos. O importante é seguir.",
    "mindos.insights.mais": "Ver detalhes",
    "mindos.estudo.titulo": "Conhecimento de hoje",
    "mindos.estudo.proximo": "Próximo passo:",
    "mindos.estudo.progresso": "{{feitos}}/{{total}} etapas — sem pressa.",
    "mindos.estudo.continuar": "Continuar",
    "mindos.estudo.concluido": "Sessão de hoje completa. Pode descansar.",
    "mindos.estudo.rodape": "Vídeo, áudio, questões e neuro ficam recolhidos abaixo.",
    "mindos.estudo.mais": "Ferramentas de estudo",
    "mindos.estudo.passo.assistir": "Assistir um vídeo",
    "mindos.estudo.passo.ouvir": "Ouvir áudio ou podcast",
    "mindos.estudo.passo.praticar": "Praticar questões",
    "mindos.estudo.passo.falar": "Falar vocabulário",
    "mindos.estudo.passo.neuro": "Neuro — revisão rápida",

    "cognitivo.titulo": "Desenvolvimento",
    "cognitivo.proximo": "Próximo bloco:",
    "cognitivo.concluido": "Sessão cognitiva de hoje completa.",
    "cognitivo.progresso": "{{feitos}}/{{total}} blocos — ~60 min no total.",
    "cognitivo.comecar": "Começar",
    "cognitivo.bloco.concluir": "Concluir bloco",
    "cognitivo.sessao.finalizar": "Finalizar sessão",
    "cognitivo.dificuldade": "Dificuldade {{n}}/10 · {{nivel}}",
    "cognitivo.objetivo": "Objetivo",
    "cognitivo.objetivo.vazio": "Defina um objetivo abaixo ou capture na inbox.",
    "cognitivo.objetivo.ajustar": "Ajustar objetivo",
    "cognitivo.objetivo.placeholder": "Ex.: Quero melhorar matemática",
    "cognitivo.objetivo.salvar": "Salvar",
    "cognitivo.agora.titulo": "Desenvolvimento",
    "cognitivo.agora.acao": "{{min}} min — {{bloco}}",
    "cognitivo.agora.dificuldade": "Dificuldade: {{n}}/10",
    "cognitivo.bloco.raciocinio": "Raciocínio",
    "cognitivo.bloco.aprendizagem": "Aprendizagem",
    "cognitivo.bloco.memoria": "Memória e recuperação",
    "cognitivo.bloco.explicacao": "Explicação",
    "cognitivo.bloco.reflexao": "Reflexão",
    "cognitivo.area.matematica": "Matemática",
    "cognitivo.area.logica": "Lógica",
    "cognitivo.area.programacao": "Programação",
    "cognitivo.area.ingles": "Inglês",
    "cognitivo.area.ciencia": "Ciência",
    "cognitivo.area.geral": "Geral",
    "cognitivo.raciocinio.apoio": "Resolva os problemas sem pressa. Errou? Anote o padrão.",
    "cognitivo.aprendizagem.apoio": "Estude o conceito. Anote o que importa para você.",
    "cognitivo.aprendizagem.livre": "Conceito do dia",
    "cognitivo.aprendizagem.notas": "Suas notas",
    "cognitivo.aprendizagem.placeholder": "Ideias, definições, exemplos…",
    "cognitivo.memoria.apoio": "Recupere de memória — sem consultar fonte.",
    "cognitivo.memoria.placeholder": "Sua resposta…",
    "cognitivo.explicacao.apoio": "Explique {{tema}} como se ensinasse alguém.",
    "cognitivo.explicacao.prompt": "o que estudou",
    "cognitivo.explicacao.placeholder": "Com suas palavras…",
    "cognitivo.conhecimento.titulo": "Salvar como conhecimento (opcional)",
    "cognitivo.conhecimento.titulo.placeholder": "Título do conceito",
    "cognitivo.reflexao.apoio": "Quatro linhas — sem formulário longo.",
    "cognitivo.reflexao.aprendi": "O que aprendi?",
    "cognitivo.reflexao.errei": "Onde errei?",
    "cognitivo.reflexao.nao_entendi": "O que ainda não entendi?",
    "cognitivo.reflexao.proximo": "Próximo passo?",
    "cognitivo.revisao.antes": "Antes de continuar: relembre {{titulo}} em 30 segundos.",
    "cognitivo.metrica.sessoes": "{{n}} sessões concluídas",
    "cognitivo.metrica.taxa": "{{n}}% acertos",
    "cognitivo.metrica.dificuldade": "nível {{n}}/10",
    "cognitivo.semana.melhorou": "Melhorou em {{area}}.",
    "cognitivo.semana.travando": "Atenção em {{area}}.",
    "cognitivo.semana.direcao": "Direção",
    "hoje.agenda.livre": "Nada urgente. Respire — ou ajuste o ritmo em Ritmo.",
    "hoje.agenda.concluido": "Tudo claro por hoje. Pode descansar.",
    "hoje.agenda.proximo.html": "Próximo: <strong>{{horario}}</strong> — {{nome}}",
    "hoje.agenda.parte.habito": "{{n}} passo",
    "hoje.agenda.parte.habitos": "{{n}} passos",
    "hoje.agenda.parte.aviso": "{{n}} aviso",
    "hoje.agenda.parte.avisos": "{{n}} avisos",
    "hoje.agenda.restante": "{{partes}} ainda hoje.",
    "hoje.lista.vazio.html":
      "Nada no ritmo ainda. Vá em <strong>Ritmo</strong> para montar o primeiro passo.",
    "hoje.lista.filtro":
      "Nada visível com os filtros atuais. Desative um modo ou marque o que importa.",
    "hoje.prioridades.rotulo": "O que importa hoje ({{atual}}/{{max}}) — toque na ☆",
    "hoje.manha.nao.esquecer.html": "<strong>Não esquecer:</strong> {{lista}}",
    "hoje.manha.de.ontem.html": "<strong>De ontem:</strong> {{texto}}",
    "hoje.manha.seu.foco.html": "<strong>Seu foco:</strong> {{lista}}",
    "hoje.relogio.em.min": "⏰ {{nome}} em {{min}} min",
    "hoje.relogio.proximo": "Próximo: {{nome}} {{countdown}}",
    "hoje.countdown.agora": "agora",
    "hoje.countdown.em.min": "em {{n}} min",
    "hoje.countdown.em.hora": "em {{h}}h{{m}}",
    "hoje.countdown.em.h": "em {{h}}h",
    "hoje.avisos.vazio.form": "Nenhum aviso agendado. Adicione acima.",
    "hoje.avisos.secao.hoje": "Hoje",
    "hoje.avisos.secao.proximos": "Próximos",
    "hoje.inbox.acao.habito": "Ritmo",
    "hoje.inbox.acao.nota": "Nota",
    "hoje.inbox.acao.depois": "Depois",
    "hoje.inbox.acao.habito.title": "Incluir no ritmo do dia",
    "hoje.inbox.acao.nota.title": "Mover para anotações de hoje",
    "hoje.inbox.acao.depois.title": "Guardar para outro dia",
    "hoje.inbox.remover.title": "Remover da inbox",
    "hoje.item.passos.title": "Toque para registrar o próximo lembrete",
    "hoje.item.importancia.title": "Toque para mudar rápido — ou use ✎ para editar tudo",
    "hoje.item.meta.title": "Editar vezes na semana",
    "hoje.item.meta.aria": "Frequência: {{freq}}. Toque para editar.",
    "hoje.item.lembretes.total": "{{n}} lembretes no dia",
    "hoje.item.lembretes.feitos": "todos os lembretes feitos",
    "hoje.item.lembrete.progresso": "lembrete {{atual}} de {{total}}",
    "hoje.item.semana.progresso": "{{feitos}}/{{alvo}} esta semana",
    "hoje.item.recorde": "recorde {{n}}",
    "hoje.item.micro.dica": "Micro-passos feitos — pode marcar o passo principal ✓",
    "hoje.item.streak.dia": "{{n}} dia",
    "hoje.item.streak.dias": "{{n}} dias",
    "hoje.item.editar.title": "Editar nome e frequência",
    "hoje.item.editar.aria": "Editar nome e frequência",
    "hoje.item.remover.title": "Remover do ritmo",
    "hoje.item.remover.aria": "Remover do ritmo",
    "hoje.item.prioridade.title": "O que importa hoje (máx. {{max}})",
    "hoje.item.prioridade.remover": "Tirar do que importa",
    "hoje.item.prioridade.marcar": "Marcar como o que importa",
    "agora.primeiro.passo.html": "Primeiro passo: <strong>{{passo}}</strong>",
    "agora.preparar": "Dica: {{lista}}",
    "agora.timer.cronometro": "Cronômetro",
    "agora.timer.foco": "Foco",
    "agora.timer.so.abrir": "Só abrir",
    "agora.timer.2min": "2 min",
    "agora.timer.5min": "5 min",
    "agora.timer.10min": "10 min",
    "agora.timer.25min": "25 min",
    "filtro.todas": "Todas",
    "categoria.geral": "Geral",
    "semana.grafico.media": "média {{n}}%",
    "semana.metas.vazio": "Inclua passos no ritmo para acompanhar a semana.",
    "semana.resumo.vazio":
      "Sua semana ainda está em branco. Inclua um ou dois passos no ritmo e volte aqui no fim da semana para ver a continuidade.",
    "semana.resumo.media": "Nos últimos 7 dias você manteve em média {{pct}}% do ritmo.",
    "semana.resumo.melhor.dia": "Seu melhor dia foi {{dia}} ({{pct}}%).",
    "semana.resumo.melhor.categoria": "{{nome}} foi sua categoria mais forte ({{pct}}% de conclusão).",
    "semana.resumo.fraca.categoria": "{{nome}} pede mais atenção ({{pct}}% esta semana).",
    "semana.resumo.metas": "{{cumpridas}} de {{total}} ritmos da semana já mantidos.",
    "semana.resumo.habito.forte": "\"{{nome}}\" está em ótimo ritmo.",
    "semana.resumo.nota.alta": "Semana sólida — continuidade é o que constrói direção.",
    "semana.resumo.nota.media": "Você está no caminho. Pequenos ajustes podem elevar o próximo ciclo.",
    "semana.resumo.nota.baixa":
      "Semana difícil? Tudo bem. O estoicismo ensina: recomeçar também é virtude.",
    "semana.plano.carregando": "Montando plano…",
    "semana.plano.erro": "IA indisponível.",
    "semana.plano.titulo.default": "Sua semana",
    "semana.plano.foco": "Foco:",
    "hoje.filosofia.coach.pesado":
      " Ontem foi pesado no diário — hoje vá com gentileza, um passo de cada vez.",
    "hoje.filosofia.coach.bom": " Ontem você registrou um bom dia — use esse impulso.",
    "hoje.filosofia.coach.reflexao":
      " Sua nota de ontem mostra reflexão — transforme isso em ação hoje.",
    "ajustes.perfil.nome": "Seu nome",
    "ajustes.perfil.nome.placeholder": "Ex.: Miguel",
  },
  en: {
    "app.title": "North",
    "header.brand": "North",
    "header.tagline": "Gives you direction — body, mind, and knowledge, without the mental load.",
    "header.day": "North",
    "nav.north": "North",
    "nav.memoria": "Memory",
    "nav.hoje": "Now",
    "nav.guia": "Guide",
    "nav.estudo": "Knowledge",
    "nav.rotina": "Rhythm",
    "nav.semana": "Direction",
    "nav.diario": "Journal",
    "nav.insights": "Continuity",
    "nav.ajustes": "Settings",
    "nav.aria": "North areas",
    "panel.hoje": "North",
    "panel.memoria": "Memory",
    "panel.guia": "Guide",
    "panel.cheguei": "What now?",
    "panel.estudo": "Knowledge",
    "panel.rotina": "Rhythm",
    "panel.semana": "Direction",
    "panel.diario": "Journal",
    "panel.insights": "Continuity",
    "panel.ajustes": "Settings",
    "panel.default": "North",
    "theme.aria": "Toggle theme",
    "guia.chamada.html":
      "<strong>First time?</strong> The <strong>Guide</strong> shows how North gives you direction in 5 min.",
    "guia.chamada.abrir": "Open Guide",
    "guia.chamada.depois": "Later",
    "dica.inicio.html":
      "<strong>Today</strong> shows one focus. The rest stays organized underneath.",
    "dica.entendi": "Got it",
    "hoje.manha.titulo": "Morning — 2 min",
    "hoje.manha.apoio": "What matters today? Three lines max.",
    "hoje.prioridade": "What matters {{n}}",
    "hoje.prioridade1": "What matters 1",
    "hoje.prioridade2": "What matters 2",
    "hoje.prioridade3": "What matters 3",
    "hoje.tema": "Weekly theme",
    "hoje.tema.placeholder": "E.g.: Body, mind, and knowledge",
    "hoje.agora": "Now",
    "hoje.inbox.titulo": "Capture — out of your head",
    "hoje.inbox.apoio": "Any thought in 10 seconds. North holds it — no pressure.",
    "hoje.inbox.placeholder": "E.g.: call the doctor, work idea...",
    "hoje.inbox.anotar": "Note",
    "hoje.inbox.vazio": "Inbox empty. When something comes up, drop it here.",
    "hoje.inbox.arquivar": "Save all and clear your head",
    "hoje.avisos.titulo": "Reminders",
    "hoje.avisos.apoio":
      "Date and time reminders — like a calendar. Turn on notifications in <strong>Settings</strong>.",
    "hoje.avisos.placeholder": "E.g.: Submit homework, doctor appointment...",
    "hoje.avisos.adicionar": "Add reminder",
    "hoje.avisos.vazio": "No reminders for today.",
    "hoje.compromissos": "Today's steps",
    "hoje.ritmo": "Weekly rhythm",
    "hoje.revisao.titulo": "Day review — 2 min",
    "hoje.revisao.apoio": "What stuck? What's for tomorrow? No judgment.",
    "hoje.nota.titulo": "Today's notes",
    "hoje.nota.placeholder": "Free form — mood, ideas, anything to remember.",
    "agora.link.cheguei": "What now? — only 2 options",
    "agora.dica": "One step only. You don't have to do everything.",
    "agora.vazio": "Nothing pending now. Rest or check your inbox.",
    "agora.mais": "More options",
    "agora.travei": "I'm stuck",
    "agora.cronometro": "Stopwatch",
    "agora.parar": "Stop",
    "agora.travei.titulo": "Stuck? Plan B — the bare minimum",
    "agora.travei.30s": "Just 30 seconds",
    "agora.travei.ok": "OK, got it",
    "cheguei.voltar": "← Back to Guide",
    "cheguei.ola": "What now?",
    "cheguei.apoio": "No huge list — tell me what just happened and I'll give you 2 options.",
    "cheguei.apoio.madrugada": "It's late — no heavy work. What just happened?",
    "cheguei.voz": "Speak — I'll understand",
    "cheguei.ou.voz": "or choose:",
    "cheguei.ou": "or",
    "cheguei.reiniciar": "Different situation",
    "cheguei.feito.titulo": "Nice.",
    "cheguei.feito.mais": "See 2 more options",
    "cheguei.ia": "✨ adjusted by AI",
    "cheguei.gatilho.chegada": "I got home",
    "cheguei.gatilho.tarefa": "I finished something",
    "cheguei.gatilho.acordar": "I just woke up",
    "cheguei.gatilho.pausa": "I need a break",
    "cheguei.gatilho.noite": "I'm winding down",
    "guia.hero.kicker": "North · v{{versao}}",
    "guia.hero.titulo": "One step at a time",
    "guia.hero.apoio":
      "{{nome}}, {{faixa}} · {{hora}}. I'm North — direction without the mental load.",
    "guia.demo.iniciar": "▶ Start 5-min walkthrough",
    "guia.cheguei.btn": "What now? — 2 options",
    "guia.progresso": "Demo walkthrough",
    "guia.reset": "Reset walkthrough progress",
    "guia.mapa.titulo": "Tab map",
    "guia.mapa.apoio": "Quick reference — only if you need it.",
    "guia.dicas.titulo": "Extra reference",
    "guia.ia.ativa": "✨ AI active on server — Neuro, Journal and Now can use intelligence.",
    "guia.ia.local":
      "⚠️ AI offline — set GROQ_API_KEY on Vercel for Neuro, Journal and What now?",
    "guia.demo.banner": "Presentation mode — step <strong>{{atual}}</strong> of {{total}}",
    "guia.demo.proximo": "Next step →",
    "guia.demo.sair": "Exit mode",
    "guia.passo.abrir": "Open and show →",
    "guia.passo.feito": "✓ Done",
    "guia.passo.marcar": "Mark as done",
    "guia.passo.falar": "<strong>What to say:</strong> {{texto}}",
    "guia.tempo.30s": "30 s",
    "guia.tempo.1min": "1 min",
    "guia.tempo.2min": "2 min",
    "guia.rota.hoje.titulo": "Today — one focus",
    "guia.rota.hoje.falar":
      "Greeting, one step, what comes next. No huge list — just direction.",
    "guia.rota.cheguei.titulo": "What now? — only 2 options",
    "guia.rota.cheguei.falar":
      "When your brain freezes, the app offers at most two contextual choices — no endless list.",
    "guia.rota.neuro.titulo": "Study → Neuro",
    "guia.rota.neuro.falar":
      "Neuroscience track: read, explain by voice or text, get feedback. The ADHD module stands out.",
    "guia.rota.diario.titulo": "Journal with AI",
    "guia.rota.diario.falar":
      "Daily notes stay safe. Tap Organize with AI for a gentle summary.",
    "guia.rota.insights.titulo": "Insights — continuity",
    "guia.rota.insights.falar": "No guilt: the app shows continuity, not pressure.",
    "guia.ref.hoje": "One focus, then what's next, relief.",
    "guia.ref.estudo": "Knowledge — video, neuro, practice.",
    "guia.ref.rotina": "Daily rhythm — adjustments tucked away.",
    "guia.ref.semana": "Week direction — numbers optional.",
    "guia.ref.diario": "Safe notes, with history.",
    "guia.ref.insights": "Gentle continuity — details tucked away.",
    "guia.ref.ajustes": "Name, schedule, sync and language.",
    "guia.mais.referencia": "Full reference",
    "guia.dica.1": "Use Chrome or Safari on your phone — voice and home screen install work best.",
    "guia.dica.2": "Allow the microphone the first time (Study → Neuro → Explain by voice only).",
    "guia.dica.3": "If something looks old, hold reload to refresh the version.",
    "guia.dica.4": "The app works offline; AI (when configured) needs internet on Vercel.",
    "guia.dica.5": "To impress: start with the walkthrough below — about 5 minutes.",
    "offline.banner":
      "No internet — your data is saved on this device. AI and sync return when you reconnect.",
    "faixa.manha": "morning",
    "faixa.tarde": "afternoon",
    "faixa.noite": "evening",
    "faixa.madrugada": "late night",
    "ajustes.idioma.titulo": "Language",
    "ajustes.idioma.apoio": "For now: Portuguese and English. The app remembers your choice.",
    "ajustes.idioma.pt": "Português",
    "ajustes.idioma.en": "English",
    "ajustes.rotina.titulo": "Your routine",
    "ajustes.rotina.apoio":
      "Tweak your times — the routine recalculates study, water and sleep automatically.",
    "ajustes.rotina.acordar": "Wake up",
    "ajustes.rotina.dormir": "Sleep",
    "ajustes.rotina.chegada": "Home arrival",
    "ajustes.rotina.tardeFim": "Hard afternoon ends",
    "ajustes.rotina.praia": "Beach work on weekends",
    "ajustes.rotina.preview": "Rhythm preview",
    "ajustes.rotina.botao": "Rebuild full routine",
    "ajustes.rotina.confirmar":
      "This updates {{total}} rhythm steps (study at {{estudo}}). Your custom ones stay. Continue?",
    "ajustes.rotina.ok": "Rhythm recalculated! {{novos}} new, {{atualizados}} updated. See Now.",
    "ajustes.rotina.erro": "Could not rebuild the routine. Try again.",
    "ajustes.rotina.perfil": "Wakes {{acordar}}, school Mon–Fri, hard afternoon {{tardeIni}}–{{tardeFim}}. Priorities: {{prioridades}}.",
    "ajustes.sobre.titulo": "About",
    "ajustes.sobre.apoio":
      "Gives you direction — body, mind, and knowledge, without the mental load. Use little. Use daily.",
    "ajustes.atualizar": "Check for updates",
    "feedback.idioma": "Language changed.",
    "feedback.guia.reset": "Walkthrough progress reset.",
    "feedback.demo.fim": "Walkthrough complete! You nailed the demo.",
    "feedback.demo.passo": "Demo — {{titulo}}",
    "rotina.adicionar.titulo": "Add to rhythm",
    "rotina.adicionar.apoio": "Tap a shortcut or type a name. Use the Today tab to check off.",
    "rotina.adicionar.placeholder": "What should the day remember?",
    "rotina.adicionar.btn": "Add",
    "rotina.opcoes.summary": "Time and importance (optional)",
    "rotina.atalho.agua": "💧 Water",
    "rotina.atalho.academia": "🏋️ Gym",
    "rotina.atalho.estudo": "🎧 Learn",
    "rotina.atalho.vocabulario": "🗣️ Vocabulary",
    "rotina.atalho.praticalivro": "📖 Practice",
    "rotina.atalho.meditar": "🧘 Meditate",
    "rotina.sugestao.usar": "Use suggestion",
    "rotina.importancia.1": "Essential",
    "rotina.importancia.2": "Important",
    "rotina.importancia.3": "Normal",
    "diario.titulo": "Journal",
    "diario.apoio": "Write freely. Tap Organize with AI for a gentle summary.",
    "diario.apoio.html":
      "Each day keeps one entry. It's the <strong>same text</strong> as <strong>Today → Today's notes</strong>. Auto-saves on every change — <strong>each save creates a version</strong> in <strong>History</strong>.",
    "diario.data": "Date",
    "diario.placeholder": "Write about this day…",
    "diario.hoje": "Go to today",
    "diario.ontem": "See yesterday",
    "diario.salvar": "Save entry",
    "diario.resumo.ia": "Organize with AI",
    "diario.historico": "History",
    "diario.historico.apoio": "Up to 2 versions per day — only when the text changes. Tap to restore.",
    "diario.historico.vazio": "No saved versions for this date yet. Write a bit — the app saves automatically.",
    "diario.busca.titulo": "Search old text",
    "diario.busca.apoio": "Searches history and the whole browser for long texts that may have gone missing.",
    "diario.busca.btn": "Search now",
    "diario.busca.vazio": "No results yet. Tap <strong>Search now</strong>.",
    "diario.entradas": "Saved entries",
    "diario.entradas.apoio": "Tap a date to open that note.",
    "diario.vazio":
      "No entries yet. Write in Today or here — they show up automatically. If yesterday's text vanished, tap <strong>See yesterday</strong> or <strong>Restore notes</strong> if shown above.",
    "semana.grafico": "Last 7 days",
    "semana.grafico.apoio": "How much of your rhythm you kept each day.",
    "semana.metas": "Week rhythm",
    "semana.metas.apoio": "How much of the rhythm you kept — no pressure.",
    "semana.resumo": "Summary",
    "semana.resumo.titulo": "Week summary",
    "semana.resumo.apoio": "A read on your last 7-day cycle.",
    "semana.plano.ia": "Suggested week direction",
    "insights.mes": "This month — continuity",
    "insights.mes.apoio": "Intensity = how much of your rhythm you kept today.",
    "sync.titulo": "Sync Mac and iPhone",
    "sync.apoio": "Same code on every device — your data stays in sync.",
    "sync.criar": "Create sync",
    "sync.codigo": "Code:",
    "sync.placeholder": "Code from your other device",
    "sync.carregando": "Loading…",
    "sync.apoio.html":
      "Create a code on this device and enter the same code on the other. Rhythm, journal and Neuro track stay in sync — even when switching hosts (GitHub → Vercel).",
    "sync.entrar": "Enter with code",
    "sync.copiar": "Copy code",
    "sync.desconectar": "Disconnect",
    "lembretes.titulo": "North nudges",
    "lembretes.apoio": "Nudges from North — works best with the iPhone home screen app.",
    "lembretes.apoio.html":
      "Install the app on your home screen to get alerts even with the browser closed. Browser menu → <strong>Add to Home Screen</strong>.",
    "lembretes.btn": "Enable reminders",
    "vercel.titulo": "Main app (Vercel)",
    "vercel.apoio": "Recommended URL on iPhone and Mac — full app + AI + auto deploy on every git push:",
    "vercel.apoio.html":
      "Recommended URL on iPhone and Mac — full app + AI + auto deploy on every <code>git push</code>: <a href=\"https://projeto-1-criar.vercel.app\" target=\"_blank\" rel=\"noopener noreferrer\">projeto-1-criar.vercel.app</a>",
    "vercel.dica": "Use the <strong>same sync code</strong> on all devices. AI via <strong>Groq</strong> on Vercel — no local fallback.",
    "backup.titulo": "Data backup",
    "backup.apoio": "Even with sync, export once in a while. Backup is an extra safety copy.",
    "backup.exportar": "Export",
    "backup.importar": "Import",
    "hoje.nota.salvar": "Save notes",
    "migracao.github.texto": "For full AI and sync, use the Vercel version:",
    "migracao.github.html":
      "New version with AI: <a data-migracao-link-vercel href=\"https://projeto-1-criar.vercel.app\">projeto-1-criar.vercel.app</a> — use the <strong>same sync code</strong>.",
    "migracao.github.ir": "Open on Vercel",
    "migracao.host.titulo": "Restore your data",
    "migracao.host.texto": "This device doesn't have your sync code yet. Connect in Settings to bring journal and rhythm.",
    "migracao.host.texto.html":
      "This address is new on this device. Your <strong>journal</strong>, rhythm and Neuro track are safe in <strong>sync</strong> — sign in with the same code you use on your phone.",
    "migracao.host.alerta":
      "⚠️ Before writing in the journal here, connect sync so you don't overwrite the cloud with empty text.",
    "migracao.host.ajustes": "Go to Settings → Sync",
    "migracao.host.exportar": "Export backup",
    "rotina.adicionar.apoio.html": "Tap a shortcut or type a name. Use the <strong>Today</strong> tab to check off.",
    "hoje.nota.apoio.html":
      "What marked this day? History lives in the <strong>Journal</strong> tab — it's the same entry as today.",
    "neuro.titulo": "Neuro — learn by explaining",
    "neuro.fase": "Phase D",
    "neuro.trilha.apoio": "Track with {{total}} modules · read → explain (voice or text) → feedback{{ia}}. Today: {{hoje}}/{{total}}.",
    "neuro.trilha.ia": " with AI",
    "neuro.pontos": "Key points",
    "neuro.explicar.dica": "As if teaching a friend — voice or text.",
    "neuro.placeholder": "Write or use the microphone above...",
    "neuro.verificar.ia": "Check with AI ✨",
    "neuro.verificar.local": "Check my explanation",
    "neuro.proximo": "Next: {{titulo}} →",
    "neuro.timer": "10 min timer",
    "neuro.voz.completa": "🎤 Explain with voice only",
    "neuro.voz.dictado": "🎤 Add by voice",
    "neuro.voz.indisponivel": "Microphone unavailable — write below.",
    "neuro.ia.carregando": "✨ AI is reading your explanation…",
    "neuro.fb.fonte": "AI correction ✨",
    "neuro.fb.pct": "{{pct}}% of the essentials",
    "neuro.fb.acertos": "You mentioned:",
    "neuro.fb.faltou": "Still worth including:",
    "neuro.fb.pergunta": "To reflect:",
    "neuro.fb.ouvir": "🔊 Hear feedback",
    "neuro.fb.responder": "🎤 Answer question",
    "common.fechar": "Close",
    "sync.aviso.firebase.html":
      "Firebase still needs setup (it's free). Ask your assistant for steps or paste the config in <code>firebase-config.js</code>.",
    "sync.status.firebase": "Firebase not configured yet.",
    "sync.status.ativo": "Sync active on this device.",
    "sync.status.sem": "No sync. Create a code or enter an existing one.",
    "sync.status.sincronizado": "Synced just now.",
    "sync.status.falha_envio": "Failed to upload. Try again.",
    "sync.status.atualizado_nuvem": "Updated from cloud.",
    "sync.status.erro_ouvir": "Error listening to cloud.",
    "sync.status.codigo_invalido": "Invalid code. Use at least 6 characters.",
    "sync.status.codigo_nao_encontrado": "Code not found. Check it or create a new sync.",
    "sync.status.criado": "Sync created. Use this code on your other device.",
    "sync.status.conectado": "Connected. Data synced.",
    "sync.status.desconectado": "Sync turned off on this device. Local data stays here.",
    "sync.status.copiado": "Code copied. Paste it on your other device.",
    "sync.status.copia_falha": "Could not copy. Write down the code: {{codigo}}",
    "sync.status.erro_criar": "Error creating sync.",
    "sync.status.erro_conectar": "Error connecting.",
    "sync.status.firebase_lib": "Firebase library did not load.",
    "sync.status.firebase_init": "Could not start Firebase. Check your configuration.",
    "lembretes.status.indisponivel": "Notifications unavailable in this browser.",
    "lembretes.status.ativo": "Reminders on — alerts at scheduled times (best with home screen app).",
    "lembretes.status.bloqueado": "Permission blocked. Enable in browser settings.",
    "lembretes.status.off": "Reminders off.",
    "lembretes.perm.indisponivel": "This browser doesn't support notifications.",
    "lembretes.perm.ativado": "Reminders enabled.",
    "lembretes.perm.negado": "Permission denied. Enable in browser settings.",
    "lembretes.perm.nao_concedida": "Permission not granted.",
    "insights.card.sequencia": "Continuity",
    "insights.card.hoje": "Today",
    "insights.card.30dias": "30 days",
    "insights.card.recorde": "Record",
    "insights.card.compromissos": "steps taken today",
    "insights.card.taxa": "rhythm kept",
    "insights.card.melhor": "best continuity",
    "streak.global.0": "Today is a fresh start — one step counts.",
    "streak.global.1": "1 day in a row. No pressure to keep going — just celebrate.",
    "streak.global.curto": "{{n}} days in a row. You're building rhythm.",
    "streak.global.medio": "{{n}} days! That's real consistency.",
    "streak.global.longo": "{{n}} days in a row — impressive, but rest if you need to.",
    "streak.habito.voltou": "Back after {{n}} days — that counts too.",
    "streak.habito.1": "1 day — a light start.",
    "streak.habito.recorde": "Record! {{n}} days in a row.",
    "streak.habito.normal": "{{n}} days in a row",
    "streak.rotulo.0": "Fresh start",
    "streak.rotulo.1": "day in a row",
    "streak.rotulo.n": "days in a row",
    "diario.salvando": "Saving…",
    "diario.salvo": "Saved at {{hora}} · {{n}} characters",
    "diario.historico.meta": "{{hora}} · {{n}} characters · {{motivo}}",
    "diario.motivo.manual": "saved by you",
    "diario.motivo.apagar": "before deleting",
    "diario.motivo.fechar": "on exit",
    "diario.motivo.auto": "automatic",
    "ajustes.sobre.versao.html": "If the version doesn't update on its own, tap <strong>Check for updates</strong> below.",
    "ajustes.versao": "Version {{v}}{{host}}",
    "ajustes.buscando": "Checking for updates…",
    "rotina.dias.todo": "every day",
    "rotina.dias.segsex": "Mon–Fri",
    "rotina.dias.sabdom": "Sat–Sun",
    "rotina.dias.nxsem": "{{n}}x/wk",
    "rotina.preset.agua": "Drink water",
    "rotina.preset.organizar": "Organize when home (10 min)",
    "rotina.preset.aprender": "Learn 15 min",
    "rotina.preset.praticalivro": "Book practice (10 min)",
    "rotina.preset.vocabulario": "Vocabulary 5 min",
    "rotina.preset.academia": "Gym",
    "rotina.preset.telas": "Screen off",
    "rotina.preset.sono": "Sleep on time",
    "rotina.preset.manha": "Plan the day (2 min)",
    "rotina.preset.praia": "Prepare beach work",
    "mindos.saudacao.manha": "Good morning",
    "mindos.saudacao.tarde": "Good afternoon",
    "mindos.saudacao.noite": "Good evening",
    "mindos.ola.nome": "{{saudacao}}, {{nome}}.",
    "north.convite.estudo": "Shall we continue studying today?",
    "north.convite.diario": "Feel like writing a little?",
    "north.convite.manha": "How do you want to start the day?",
    "north.convite.calmo": "One step at a time — ready when you are.",
    "north.slogan": "Less to Think. More to Do.",
    "north.pergunta": "How are you today?",
    "north.estado.aria": "How are you today",
    "north.estado.sobrecarregado": "Overwhelmed",
    "north.estado.sobrecarregado.emoji": "😵",
    "north.estado.normal": "Normal",
    "north.estado.normal.emoji": "😐",
    "north.estado.bem": "Good",
    "north.estado.bem.emoji": "🙂",
    "north.estado.focado": "Focused",
    "north.estado.focado.emoji": "🔥",
    "north.transicao": "Let's go this way.",
    "north.foco.rotulo": "Your next step",
    "north.foco.aprender": "Learn",
    "north.foco.corpo": "Body",
    "north.foco.agora": "Now",
    "north.foco.ingles": "English",
    "north.foco.duracao": "{{n}} minutes",
    "north.foco.desc.aprender": "Build understanding and conversation.",
    "north.foco.desc.corpo": "Move with intention.",
    "north.foco.desc.geral": "One step at a time — no need to think about everything.",
    "north.comecar": "Start →",
    "north.depois": "Up next",
    "north.estado.trocar": "Change state",
    "north.livre": "Nothing urgent now. Breathe.",
    "north.feito": "Done.",
    "north.feito.apoio": "You moved forward today.",
    "north.feito.proximo": "Next step ready.",
    "north.continuar": "Continue →",
    "north.encerrar": "End →",
    "north.foco.modo": "Focus",
    "north.finalizar": "Finish",
    "north.pausar": "Pause",
    "north.retomar": "Resume",
    "north.memoria.titulo": "Memory",
    "north.memoria.apoio": "Consult — don't act. Everything that matters, stored.",
    "north.memoria.conhecimento": "Knowledge",
    "north.memoria.conhecimento.apoio": "Study, tracks, and cognitive sessions.",
    "north.memoria.diario": "Journal",
    "north.memoria.diario.apoio": "Records, reflections, and history.",
    "north.memoria.direcao": "Direction",
    "north.memoria.direcao.apoio": "Week, priorities, and plan.",
    "north.memoria.continuidade": "Continuity",
    "north.memoria.continuidade.apoio": "Patterns, insights, and progress.",
    "north.memoria.ritmo": "Rhythm",
    "north.memoria.ritmo.apoio": "Day map and habits — adjust when you want.",
    "mindos.sono": "Sleep routine: {{duracao}}.",
    "mindos.foco.rotulo": "Today's focus:",
    "mindos.comecar": "Start",
    "mindos.depois.titulo": "After that",
    "mindos.duracao.min": "{{n}} minutes",
    "mindos.rodape": "Your mind is clear. The rest is already organized.",
    "mindos.livre.tudo": "Nothing urgent now. You can breathe.",
    "mindos.rodape.leve": "Just this for now. The rest can wait.",
    "mindos.rodape.minimo": "One step at a time.",
    "mindos.estado.aria": "How is your head today",
    "mindos.estado.pergunta": "How is your head?",
    "mindos.estado.melhor": "Feeling better",
    "mindos.estado.organizado": "Clear",
    "mindos.estado.motivado": "Motivated",
    "mindos.estado.distraido": "Distracted",
    "mindos.estado.ansioso": "Anxious",
    "mindos.estado.cansado": "Tired",
    "mindos.estado.sobrecarregado": "Overwhelmed",
    "hoje.mais": "Day tools",
    "hoje.mapa.mais": "Rhythm map",
    "mindos.rotina.titulo": "Today's rhythm",
    "mindos.rotina.apoio": "Your day map — without holding it all in your head.",
    "mindos.rotina.vazio": "Nothing scheduled today. Breathe.",
    "mindos.rotina.rodape": "Adjust the map below. On Now, only the next step.",
    "mindos.rotina.mais": "Adjust the day map",
    "mindos.semana.titulo": "Week direction",
    "mindos.semana.tema.placeholder": "Body, mind, and knowledge",
    "mindos.semana.progresso": "{{feitos}} steps taken this week — no pressure.",
    "mindos.semana.foco": "Focus now:",
    "mindos.semana.rodape": "Numbers stay in the background. Direction comes first.",
    "mindos.semana.mais": "See week numbers",
    "mindos.insights.titulo": "Continuity",
    "mindos.insights.default": "Every return counts. Direction continues.",
    "mindos.insights.passos": "{{n}} steps this week — no pressure.",
    "mindos.insights.sem.passos": "No rush. One step is enough.",
    "mindos.insights.rodape": "Numbers stay tucked away. Keep going.",
    "mindos.insights.mais": "See details",
    "mindos.estudo.titulo": "Today's knowledge",
    "mindos.estudo.proximo": "Next step:",
    "mindos.estudo.progresso": "{{feitos}}/{{total}} steps — no rush.",
    "mindos.estudo.continuar": "Continue",
    "mindos.estudo.concluido": "Today's session is complete. You can rest.",
    "mindos.estudo.rodape": "Video, audio, questions, and neuro stay tucked below.",
    "mindos.estudo.mais": "Study tools",
    "mindos.estudo.passo.assistir": "Watch a video",
    "mindos.estudo.passo.ouvir": "Listen to audio or a podcast",
    "mindos.estudo.passo.praticar": "Practice questions",
    "mindos.estudo.passo.falar": "Speak vocabulary",
    "mindos.estudo.passo.neuro": "Neuro — quick review",

    "cognitivo.titulo": "Development",
    "cognitivo.proximo": "Next block:",
    "cognitivo.concluido": "Today's cognitive session is complete.",
    "cognitivo.progresso": "{{feitos}}/{{total}} blocks — ~60 min total.",
    "cognitivo.comecar": "Start",
    "cognitivo.bloco.concluir": "Complete block",
    "cognitivo.sessao.finalizar": "Finish session",
    "cognitivo.dificuldade": "Difficulty {{n}}/10 · {{nivel}}",
    "cognitivo.objetivo": "Goal",
    "cognitivo.objetivo.vazio": "Set a goal below or capture in inbox.",
    "cognitivo.objetivo.ajustar": "Adjust goal",
    "cognitivo.objetivo.placeholder": "E.g. I want to improve math",
    "cognitivo.objetivo.salvar": "Save",
    "cognitivo.agora.titulo": "Development",
    "cognitivo.agora.acao": "{{min}} min — {{bloco}}",
    "cognitivo.agora.dificuldade": "Difficulty: {{n}}/10",
    "cognitivo.bloco.raciocinio": "Reasoning",
    "cognitivo.bloco.aprendizagem": "Learning",
    "cognitivo.bloco.memoria": "Memory & recall",
    "cognitivo.bloco.explicacao": "Explanation",
    "cognitivo.bloco.reflexao": "Reflection",
    "cognitivo.area.matematica": "Math",
    "cognitivo.area.logica": "Logic",
    "cognitivo.area.programacao": "Programming",
    "cognitivo.area.ingles": "English",
    "cognitivo.area.ciencia": "Science",
    "cognitivo.area.geral": "General",
    "cognitivo.raciocinio.apoio": "Solve at your pace. Wrong? Note the pattern.",
    "cognitivo.aprendizagem.apoio": "Study the concept. Note what matters to you.",
    "cognitivo.aprendizagem.livre": "Concept of the day",
    "cognitivo.aprendizagem.notas": "Your notes",
    "cognitivo.aprendizagem.placeholder": "Ideas, definitions, examples…",
    "cognitivo.memoria.apoio": "Recall from memory — no peeking.",
    "cognitivo.memoria.placeholder": "Your answer…",
    "cognitivo.explicacao.apoio": "Explain {{tema}} as if teaching someone.",
    "cognitivo.explicacao.prompt": "what you studied",
    "cognitivo.explicacao.placeholder": "In your own words…",
    "cognitivo.conhecimento.titulo": "Save as knowledge (optional)",
    "cognitivo.conhecimento.titulo.placeholder": "Concept title",
    "cognitivo.reflexao.apoio": "Four lines — no long form.",
    "cognitivo.reflexao.aprendi": "What did I learn?",
    "cognitivo.reflexao.errei": "Where did I err?",
    "cognitivo.reflexao.nao_entendi": "What don't I get yet?",
    "cognitivo.reflexao.proximo": "Next step?",
    "cognitivo.revisao.antes": "Before continuing: recall {{titulo}} in 30 seconds.",
    "cognitivo.metrica.sessoes": "{{n}} sessions completed",
    "cognitivo.metrica.taxa": "{{n}}% correct",
    "cognitivo.metrica.dificuldade": "level {{n}}/10",
    "cognitivo.semana.melhorou": "Improved in {{area}}.",
    "cognitivo.semana.travando": "Watch {{area}}.",
    "cognitivo.semana.direcao": "Direction",
    "hoje.agenda.livre": "Nothing urgent. Breathe — or adjust rhythm under Rhythm.",
    "hoje.agenda.concluido": "All clear for today. You can rest.",
    "hoje.agenda.proximo.html": "Next: <strong>{{horario}}</strong> — {{nome}}",
    "hoje.agenda.parte.habito": "{{n}} step",
    "hoje.agenda.parte.habitos": "{{n}} steps",
    "hoje.agenda.parte.aviso": "{{n}} reminder",
    "hoje.agenda.parte.avisos": "{{n}} reminders",
    "hoje.agenda.restante": "{{partes}} still today.",
    "hoje.lista.vazio.html":
      "Nothing in your rhythm yet. Go to <strong>Rhythm</strong> to set the first step.",
    "hoje.lista.filtro":
      "Nothing visible with current filters. Turn off a mode or mark what matters.",
    "hoje.prioridades.rotulo": "What matters today ({{atual}}/{{max}}) — tap ☆",
    "hoje.manha.nao.esquecer.html": "<strong>Don't forget:</strong> {{lista}}",
    "hoje.manha.de.ontem.html": "<strong>From yesterday:</strong> {{texto}}",
    "hoje.manha.seu.foco.html": "<strong>Your focus:</strong> {{lista}}",
    "hoje.relogio.em.min": "⏰ {{nome}} in {{min}} min",
    "hoje.relogio.proximo": "Next: {{nome}} {{countdown}}",
    "hoje.countdown.agora": "now",
    "hoje.countdown.em.min": "in {{n}} min",
    "hoje.countdown.em.hora": "in {{h}}h{{m}}",
    "hoje.countdown.em.h": "in {{h}}h",
    "hoje.avisos.vazio.form": "No reminders scheduled. Add one above.",
    "hoje.avisos.secao.hoje": "Today",
    "hoje.avisos.secao.proximos": "Upcoming",
    "hoje.inbox.acao.habito": "Rhythm",
    "hoje.inbox.acao.nota": "Note",
    "hoje.inbox.acao.depois": "Later",
    "hoje.inbox.acao.habito.title": "Add to day rhythm",
    "hoje.inbox.acao.nota.title": "Move to today's notes",
    "hoje.inbox.acao.depois.title": "Save for another day",
    "hoje.inbox.remover.title": "Remove from inbox",
    "hoje.item.passos.title": "Tap to log the next reminder",
    "hoje.item.importancia.title": "Tap to change quickly — or use ✎ to edit everything",
    "hoje.item.meta.title": "Edit times per week",
    "hoje.item.meta.aria": "Frequency: {{freq}}. Tap to edit.",
    "hoje.item.lembretes.total": "{{n}} reminders today",
    "hoje.item.lembretes.feitos": "all reminders done",
    "hoje.item.lembrete.progresso": "reminder {{atual}} of {{total}}",
    "hoje.item.semana.progresso": "{{feitos}}/{{alvo}} this week",
    "hoje.item.recorde": "record {{n}}",
    "hoje.item.micro.dica": "Micro-steps done — you can check off the main step ✓",
    "hoje.item.streak.dia": "{{n}} day",
    "hoje.item.streak.dias": "{{n}} days",
    "hoje.item.editar.title": "Edit name and frequency",
    "hoje.item.editar.aria": "Edit name and frequency",
    "hoje.item.remover.title": "Remove from rhythm",
    "hoje.item.remover.aria": "Remove from rhythm",
    "hoje.item.prioridade.title": "Today's priority (max {{max}})",
    "hoje.item.prioridade.remover": "Remove priority",
    "hoje.item.prioridade.marcar": "Mark as priority",
    "agora.primeiro.passo.html": "First step: <strong>{{passo}}</strong>",
    "agora.preparar": "Tip: {{lista}}",
    "agora.timer.cronometro": "Stopwatch",
    "agora.timer.foco": "Focus",
    "agora.timer.so.abrir": "Just open",
    "agora.timer.2min": "2 min",
    "agora.timer.5min": "5 min",
    "agora.timer.10min": "10 min",
    "agora.timer.25min": "25 min",
    "filtro.todas": "All",
    "categoria.geral": "General",
    "semana.grafico.media": "avg {{n}}%",
    "semana.metas.vazio": "Add steps to your rhythm to follow the week.",
    "semana.resumo.vazio":
      "Your week is still blank. Add one or two rhythm steps and come back at week's end to see continuity.",
    "semana.resumo.media": "Over the last 7 days you kept an average of {{pct}}% of your rhythm.",
    "semana.resumo.melhor.dia": "Your best day was {{dia}} ({{pct}}%).",
    "semana.resumo.melhor.categoria": "{{nome}} was your strongest category ({{pct}}% completion).",
    "semana.resumo.fraca.categoria": "{{nome}} needs more attention ({{pct}}% this week).",
    "semana.resumo.metas": "{{cumpridas}} of {{total}} week rhythms already held.",
    "semana.resumo.habito.forte": "\"{{nome}}\" is in great rhythm.",
    "semana.resumo.nota.alta": "Solid week — continuity is what builds direction.",
    "semana.resumo.nota.media": "You're on track. Small tweaks can lift the next cycle.",
    "semana.resumo.nota.baixa": "Hard week? That's OK. Stoicism teaches: starting again is virtue too.",
    "semana.plano.carregando": "Building plan…",
    "semana.plano.erro": "AI unavailable.",
    "semana.plano.titulo.default": "Your week",
    "semana.plano.foco": "Focus:",
    "hoje.filosofia.coach.pesado":
      " Yesterday felt heavy in your journal — go gently today, one step at a time.",
    "hoje.filosofia.coach.bom": " You logged a good day yesterday — ride that momentum.",
    "hoje.filosofia.coach.reflexao":
      " Yesterday's note shows reflection — turn that into action today.",
    "ajustes.perfil.nome": "Your name",
    "ajustes.perfil.nome.placeholder": "E.g.: Miguel",
  },
};
