/** Dicionários PT / EN — chaves estáveis para i18n. */

export const TRADUCOES = {
  pt: {
    "app.title": "Agenda — Seu dia",
    "header.brand": "Agenda",
    "header.day": "Seu dia",
    "nav.hoje": "Hoje",
    "nav.guia": "Guia",
    "nav.estudo": "Estudo",
    "nav.rotina": "Rotina",
    "nav.semana": "Semana",
    "nav.diario": "Diário",
    "nav.insights": "Insights",
    "nav.ajustes": "Ajustes",
    "nav.aria": "Seções do app",
    "panel.hoje": "Seu dia",
    "panel.guia": "Guia",
    "panel.cheguei": "E agora?",
    "panel.estudo": "Estudo",
    "panel.rotina": "Sua rotina",
    "panel.semana": "Sua semana",
    "panel.diario": "Diário",
    "panel.insights": "Insights",
    "panel.ajustes": "Ajustes",
    "panel.default": "Agenda",
    "theme.aria": "Alternar tema",
    "guia.chamada.html":
      "<strong>Nova aqui?</strong> O <strong>Guia</strong> tem o roteiro de 5 min para mostrar o app com confiança.",
    "guia.chamada.abrir": "Abrir Guia",
    "guia.chamada.depois": "Depois",
    "dica.inicio.html":
      "<strong>Hoje</strong> é sua aba principal: <strong>Agora</strong> diz o próximo passo. Marque até <strong>3 prioridades</strong> com ☆.",
    "dica.entendi": "Entendi",
    "hoje.manha.titulo": "Manhã — 2 min",
    "hoje.manha.apoio": "O que importa hoje? Três linhas no máximo.",
    "hoje.prioridade": "Prioridade {{n}}",
    "hoje.prioridade1": "Prioridade 1",
    "hoje.prioridade2": "Prioridade 2",
    "hoje.prioridade3": "Prioridade 3",
    "hoje.tema": "Tema da semana",
    "hoje.tema.placeholder": "Ex.: Conhecimento e rotina",
    "hoje.agora": "Agora",
    "hoje.inbox.titulo": "Inbox — captura rápida",
    "hoje.inbox.apoio": "Qualquer pensamento em 10 segundos. Organize depois — sem pressão.",
    "hoje.inbox.placeholder": "Ex.: ligar pro médico, ideia do trabalho...",
    "hoje.inbox.anotar": "Anotar",
    "hoje.inbox.vazio": "Nada na inbox. Quando surgir algo, jogue aqui.",
    "hoje.inbox.arquivar": "Guardar tudo e limpar a cabeça",
    "hoje.avisos.titulo": "Avisos",
    "hoje.avisos.apoio":
      "Lembretes com data e hora — como no calendário. Ative notificações em <strong>Ajustes</strong>.",
    "hoje.avisos.placeholder": "Ex.: Entregar trabalho, consulta médica...",
    "hoje.avisos.adicionar": "Adicionar aviso",
    "hoje.avisos.vazio": "Nenhum aviso para hoje.",
    "hoje.compromissos": "Compromissos de hoje",
    "hoje.ritmo": "Ritmo da semana",
    "hoje.revisao.titulo": "Revisão do dia — 2 min",
    "hoje.revisao.apoio": "O que ficou? O que amanhã? Sem julgamento.",
    "hoje.nota.titulo": "Anotações do dia",
    "hoje.nota.placeholder": "Livre — humor, ideias, o que quiser lembrar.",
    "agora.link.cheguei": "E agora? — só 2 opções",
    "agora.dica": "Um passo só. Sem precisar fazer tudo.",
    "agora.vazio": "Nada pendente agora. Descanse ou revise a inbox.",
    "agora.mais": "Mais opções",
    "agora.travei": "Travei",
    "agora.cronometro": "Cronômetro",
    "agora.parar": "Parar",
    "agora.travei.titulo": "Travou? Plano B — só o mínimo",
    "agora.travei.30s": "Só 30 segundos",
    "agora.travei.ok": "Ok, entendi",
    "cheguei.voltar": "← Voltar ao Guia",
    "cheguei.ola": "E agora?",
    "cheguei.apoio": "Sem lista enorme — diga o que acabou de acontecer e eu monto 2 opções.",
    "cheguei.apoio.madrugada": "É madrugada — nada de trabalho pesado. Diga o que acabou de acontecer:",
    "cheguei.voz": "Falar — eu entendo",
    "cheguei.ou.voz": "ou escolha:",
    "cheguei.ou": "ou",
    "cheguei.reiniciar": "Outra situação",
    "cheguei.feito.titulo": "Boa.",
    "cheguei.feito.mais": "Ver mais 2 opções",
    "cheguei.ia": "✨ ajustado pela IA",
    "cheguei.gatilho.chegada": "Cheguei em casa",
    "cheguei.gatilho.tarefa": "Completei uma tarefa",
    "cheguei.gatilho.acordar": "Acabei de acordar",
    "cheguei.gatilho.pausa": "Preciso de uma pausa",
    "cheguei.gatilho.noite": "Vou desacelerar",
    "guia.hero.kicker": "Guia do app · v{{versao}}",
    "guia.hero.titulo": "Tudo que você precisa mostrar — em um lugar só",
    "guia.hero.apoio":
      "{{faixa}} · {{hora}}. App feito para TDAH: poucas escolhas, passos pequenos, sem culpa.",
    "guia.demo.iniciar": "▶ Iniciar roteiro de 5 min",
    "guia.cheguei.btn": "E agora? — 2 opções",
    "guia.progresso": "Roteiro de demonstração",
    "guia.reset": "Zerar progresso do roteiro",
    "guia.mapa.titulo": "Mapa rápido das abas",
    "guia.mapa.apoio": "Toque para ir direto. <em>E agora?</em> não está na barra — fica aqui e em Hoje.",
    "guia.dicas.titulo": "Antes de mostrar para alguém",
    "guia.ia.ativa": "✨ IA ativa no servidor — Neuro, Diário e Agora podem usar inteligência.",
    "guia.ia.local":
      "⚠️ IA offline — configure GROQ_API_KEY no Vercel para Neuro, Diário e Cheguei.",
    "guia.demo.banner": "Modo apresentação — passo <strong>{{atual}}</strong> de {{total}}",
    "guia.demo.proximo": "Próximo passo →",
    "guia.demo.sair": "Sair do modo",
    "guia.passo.abrir": "Abrir e mostrar →",
    "guia.passo.feito": "✓ Feito",
    "guia.passo.marcar": "Marcar como feito",
    "guia.passo.falar": "<strong>O que dizer:</strong> {{texto}}",
    "guia.tempo.30s": "30 s",
    "guia.tempo.1min": "1 min",
    "guia.tempo.2min": "2 min",
    "guia.rota.hoje.titulo": "Hoje — centro do dia",
    "guia.rota.hoje.falar":
      "Hábitos, progresso da semana e a sugestão do momento. Mostre marcar um hábito e o bloco Agora.",
    "guia.rota.cheguei.titulo": "E agora? — só 2 opções",
    "guia.rota.cheguei.falar":
      "Quando a cabeça trava, o app oferece no máximo duas escolhas contextuais — sem lista infinita.",
    "guia.rota.neuro.titulo": "Estudo → Neuro",
    "guia.rota.neuro.falar":
      "Trilha de neurociência: ler, explicar com voz ou texto e receber feedback. Módulo TDAH impressiona.",
    "guia.rota.diario.titulo": "Diário com IA",
    "guia.rota.diario.falar":
      "Anotações do dia ficam seguras. Toque em Organizar com IA para um resumo gentil.",
    "guia.rota.insights.titulo": "Insights — streak gentil",
    "guia.rota.insights.falar": "Sem culpa: sequências e padrões mostram progresso real, não cobrança.",
    "guia.ref.hoje": "Checklist, Agora, inbox, avisos e revisão do dia.",
    "guia.ref.estudo": "Neuro, livros, vídeos, prática de inglês e pronúncia.",
    "guia.ref.rotina": "Montar hábitos com IA ou editar a rotina completa.",
    "guia.ref.semana": "Visão da semana e plano inteligente.",
    "guia.ref.diario": "Notas por dia — dados sagrados, com histórico.",
    "guia.ref.insights": "Sequências, taxa de conclusão e calendário de hábitos.",
    "guia.ref.ajustes": "Sync, lembretes, exportar dados e versão do app.",
    "guia.dica.1": "Use Chrome ou Safari no celular — voz e instalação na tela inicial funcionam melhor.",
    "guia.dica.2": "Permita o microfone na primeira vez (Estudo → Neuro → Explicar só com voz).",
    "guia.dica.3": "Se algo parecer antigo, segure o botão de recarregar para atualizar a versão.",
    "guia.dica.4": "O app funciona offline; IA (quando configurada) precisa de internet no Vercel.",
    "guia.dica.5": "Para impressionar: comece pelo roteiro abaixo — leva cerca de 5 minutos.",
    "faixa.manha": "manhã",
    "faixa.tarde": "tarde",
    "faixa.noite": "noite",
    "faixa.madrugada": "madrugada",
    "ajustes.idioma.titulo": "Idioma",
    "ajustes.idioma.apoio": "Por enquanto: português e inglês. O app lembra sua escolha.",
    "ajustes.idioma.pt": "Português",
    "ajustes.idioma.en": "English",
    "ajustes.rotina.titulo": "Sua rotina",
    "ajustes.rotina.apoio":
      "Ajuste seus horários — a rotina recalcula estudo, água e sono automaticamente.",
    "ajustes.rotina.acordar": "Acordar",
    "ajustes.rotina.dormir": "Dormir",
    "ajustes.rotina.chegada": "Chego em casa",
    "ajustes.rotina.tardeFim": "Fim da tarde difícil",
    "ajustes.rotina.praia": "Trabalho na praia no fim de semana",
    "ajustes.rotina.preview": "Prévia da rotina",
    "ajustes.rotina.botao": "Remontar rotina completa",
    "ajustes.rotina.confirmar":
      "Vai atualizar {{total}} hábitos da rotina (estudo às {{estudo}}). Hábitos personalizados não são apagados. Continuar?",
    "ajustes.rotina.ok": "Rotina remontada! {{novos}} novo(s), {{atualizados}} atualizado(s). Veja em Hoje.",
    "ajustes.rotina.erro": "Não foi possível remontar a rotina. Tente de novo.",
    "ajustes.rotina.perfil": "Acorda {{acordar}}, escola seg–sex, tarde difícil {{tardeIni}}–{{tardeFim}}. Prioridades: {{prioridades}}.",
    "ajustes.sobre.titulo": "Sobre",
    "ajustes.sobre.apoio": "Sua agenda pessoal — compromissos, anotações e visão da semana. Use pouco. Use todo dia.",
    "ajustes.atualizar": "Buscar atualização",
    "feedback.idioma": "Idioma alterado.",
    "feedback.guia.reset": "Progresso do roteiro zerado.",
    "feedback.demo.fim": "Roteiro completo! Você arrasou na demonstração.",
    "feedback.demo.passo": "Demonstração — {{titulo}}",
    "rotina.adicionar.titulo": "Adicionar hábito",
    "rotina.adicionar.apoio": "Toque num atalho ou escreva o nome. Use a aba Hoje para marcar.",
    "rotina.adicionar.placeholder": "Nome do hábito...",
    "rotina.adicionar.btn": "Adicionar",
    "rotina.opcoes.summary": "Horário e importância (opcional)",
    "rotina.atalho.agua": "💧 Água",
    "rotina.atalho.academia": "🏋️ Academia",
    "rotina.atalho.estudo": "🎧 Aprender",
    "rotina.atalho.vocabulario": "🗣️ Vocabulário",
    "rotina.atalho.praticalivro": "📖 Prática",
    "rotina.atalho.meditar": "🧘 Meditar",
    "rotina.sugestao.usar": "Usar sugestão",
    "rotina.importancia.1": "Essencial",
    "rotina.importancia.2": "Importante",
    "rotina.importancia.3": "Normal",
    "diario.titulo": "Diário",
    "diario.apoio": "Escreva livremente. Toque em Organizar com IA para um resumo gentil.",
    "diario.apoio.html":
      "Cada dia guarda uma entrada. É o <strong>mesmo texto</strong> de <strong>Hoje → Anotações do dia</strong>. Salva sozinho a cada alteração — <strong>uma versão nova a cada salvamento</strong> fica em <strong>Histórico</strong>.",
    "diario.data": "Data",
    "diario.placeholder": "Escreva sobre este dia…",
    "diario.hoje": "Ir para hoje",
    "diario.ontem": "Ver ontem",
    "diario.salvar": "Salvar entrada",
    "diario.resumo.ia": "Organizar com IA",
    "diario.historico": "Histórico",
    "diario.historico.apoio": "Uma versão nova a cada salvamento automático ou manual. Toque para restaurar.",
    "diario.historico.vazio":
      "Ainda sem versões guardadas para esta data. Escreva um pouco — o app salva automaticamente.",
    "diario.busca.titulo": "Busca de texto antigo",
    "diario.busca.apoio": "Vasculha o histórico e todo o navegador por textos longos que possam ter sumido.",
    "diario.busca.btn": "Procurar agora",
    "diario.busca.vazio": "Nenhum resultado ainda. Toque em <strong>Procurar agora</strong>.",
    "diario.entradas": "Entradas salvas",
    "diario.entradas.apoio": "Toque numa data para abrir aquela nota.",
    "diario.vazio":
      "Nenhuma entrada ainda. Escreva na aba Hoje ou aqui — elas aparecem automaticamente. Se você escreveu ontem e sumiu, toque em <strong>Ver ontem</strong> ou use <strong>Restaurar anotações</strong> se aparecer acima.",
    "semana.grafico": "Últimos 7 dias",
    "semana.grafico.apoio": "Porcentagem de hábitos concluídos por dia.",
    "semana.metas": "Metas da semana",
    "semana.metas.apoio": "Quanto falta para cumprir cada meta semanal.",
    "semana.resumo": "Resumo",
    "semana.resumo.titulo": "Resumo da semana",
    "semana.resumo.apoio": "Uma leitura do seu último ciclo de 7 dias.",
    "semana.plano.ia": "Plano inteligente da semana",
    "insights.mes": "Este mês — não quebre a corrente",
    "insights.mes.apoio": "Intensidade = quanto da agenda do dia você concluiu.",
    "sync.titulo": "Sincronizar Mac e iPhone",
    "sync.apoio": "Mesmo código em todos os aparelhos — seus dados ficam iguais.",
    "sync.criar": "Criar sincronização",
    "sync.codigo": "Código:",
    "sync.placeholder": "Código do outro aparelho",
    "sync.carregando": "Carregando…",
    "sync.apoio.html":
      "Crie um código neste aparelho e digite o mesmo código no outro. Assim hábitos, diário e trilha Neuro ficam iguais — inclusive ao trocar de endereço (GitHub → Vercel).",
    "sync.entrar": "Entrar com código",
    "sync.copiar": "Copiar código",
    "sync.desconectar": "Desconectar",
    "lembretes.titulo": "Lembretes no celular",
    "lembretes.apoio": "Notificações para hábitos e avisos — funciona melhor no iPhone instalado na tela inicial.",
    "lembretes.apoio.html":
      "Instale o app na tela inicial para receber avisos mesmo com o navegador fechado. Abra o menu do navegador → <strong>Adicionar à tela inicial</strong>.",
    "lembretes.btn": "Ativar lembretes",
    "vercel.titulo": "App principal (Vercel)",
    "vercel.apoio": "URL recomendada no iPhone e no Mac — app completo + IA + deploy automático a cada git push:",
    "vercel.apoio.html":
      "URL recomendada no iPhone e no Mac — app completo + IA + deploy automático a cada <code>git push</code>: <a href=\"https://projeto-1-criar.vercel.app\" target=\"_blank\" rel=\"noopener noreferrer\">projeto-1-criar.vercel.app</a>",
    "vercel.dica": "Use o <strong>mesmo código de sync</strong> em todos os aparelhos. IA via <strong>Groq</strong> no Vercel — sem fallback local.",
    "backup.titulo": "Backup dos dados",
    "backup.apoio": "Mesmo com sync, exporte de vez em quando. O backup é uma cópia de segurança extra.",
    "backup.exportar": "Exportar",
    "backup.importar": "Importar",
    "hoje.nota.salvar": "Salvar anotações",
    "migracao.github.texto": "Para IA completa e sync, use a versão no Vercel:",
    "migracao.github.html":
      "Nova versão com IA: <a data-migracao-link-vercel href=\"https://projeto-1-criar.vercel.app\">projeto-1-criar.vercel.app</a> — use o <strong>mesmo código de sync</strong>.",
    "migracao.github.ir": "Abrir no Vercel",
    "migracao.host.titulo": "Restaurar seus dados",
    "migracao.host.texto": "Este aparelho ainda não tem seu código de sync. Conecte em Ajustes para trazer diário e hábitos.",
    "migracao.host.texto.html":
      "Este endereço é novo neste aparelho. Seu <strong>diário</strong>, hábitos e trilha Neuro estão seguros na <strong>sincronização</strong> — entre com o mesmo código que você já usa no celular.",
    "migracao.host.alerta":
      "⚠️ Antes de escrever no diário aqui, conecte o sync para não sobrescrever a nuvem com texto vazio.",
    "migracao.host.ajustes": "Ir para Ajustes → Sync",
    "migracao.host.exportar": "Exportar backup",
    "rotina.adicionar.apoio.html": "Toque num atalho ou escreva o nome. Use a aba <strong>Hoje</strong> para marcar.",
    "hoje.nota.apoio.html":
      "O que marcou este dia? O histórico fica na aba <strong>Diário</strong> — é a mesma entrada de hoje.",
    "neuro.titulo": "Neuro — aprender explicando",
    "neuro.fase": "Fase D",
    "neuro.trilha.apoio": "Trilha com {{total}} módulos · leia → explique (voz ou texto) → feedback{{ia}}. Hoje: {{hoje}}/{{total}}.",
    "neuro.trilha.ia": " com IA",
    "neuro.pontos": "Pontos-chave",
    "neuro.explicar.dica": "Como se estivesse ensinando uma amiga — voz ou texto.",
    "neuro.placeholder": "Escreva ou use o microfone acima...",
    "neuro.verificar.ia": "Verificar com IA ✨",
    "neuro.verificar.local": "Verificar minha explicação",
    "neuro.proximo": "Próximo: {{titulo}} →",
    "neuro.timer": "Timer 10 min",
    "neuro.voz.completa": "🎤 Explicar só com voz",
    "neuro.voz.dictado": "🎤 Acrescentar por voz",
    "neuro.voz.indisponivel": "Microfone indisponível — escreva abaixo.",
    "neuro.ia.carregando": "✨ A IA está lendo sua explicação…",
    "neuro.fb.fonte": "Correção com IA ✨",
    "neuro.fb.pct": "{{pct}}% do essencial",
    "neuro.fb.acertos": "Você mencionou:",
    "neuro.fb.faltou": "Ainda vale incluir:",
    "neuro.fb.pergunta": "Pra pensar:",
    "neuro.fb.ouvir": "🔊 Ouvir feedback",
    "neuro.fb.responder": "🎤 Responder pergunta",
    "common.fechar": "Fechar",
    "sync.aviso.firebase.html":
      "Ainda falta configurar o Firebase (é grátis). Peça ao assistente o passo a passo ou cole a config em <code>firebase-config.js</code>.",
    "sync.status.firebase": "Firebase ainda não configurado.",
    "sync.status.ativo": "Sincronização ativa neste aparelho.",
    "sync.status.sem": "Sem sincronização. Crie um código ou entre com um existente.",
    "sync.status.sincronizado": "Sincronizado agora.",
    "sync.status.falha_envio": "Falha ao enviar para a nuvem. Tente de novo.",
    "sync.status.atualizado_nuvem": "Atualizado da nuvem.",
    "sync.status.erro_ouvir": "Erro ao ouvir a nuvem.",
    "sync.status.codigo_invalido": "Código inválido. Use pelo menos 6 caracteres.",
    "sync.status.codigo_nao_encontrado": "Código não encontrado. Confira ou crie uma sincronização nova.",
    "sync.status.criado": "Sincronização criada. Use este código no outro aparelho.",
    "sync.status.conectado": "Conectado. Dados sincronizados.",
    "sync.status.desconectado": "Sincronização desligada neste aparelho. Os dados locais continuam aqui.",
    "sync.status.copiado": "Código copiado. Cole no outro aparelho.",
    "sync.status.copia_falha": "Não deu para copiar. Anote o código: {{codigo}}",
    "sync.status.erro_criar": "Erro ao criar sincronização.",
    "sync.status.erro_conectar": "Erro ao conectar.",
    "sync.status.firebase_lib": "Biblioteca Firebase não carregou.",
    "sync.status.firebase_init": "Não foi possível iniciar o Firebase. Confira a configuração.",
    "lembretes.status.indisponivel": "Notificações não disponíveis neste navegador.",
    "lembretes.status.ativo": "Lembretes ativos — avisos no horário (melhor com app na tela inicial).",
    "lembretes.status.bloqueado": "Permissão bloqueada. Libere nas configurações do navegador.",
    "lembretes.status.off": "Lembretes desligados.",
    "lembretes.perm.indisponivel": "Este navegador não suporta notificações.",
    "lembretes.perm.ativado": "Lembretes ativados.",
    "lembretes.perm.negado": "Permissão negada. Ative nas configurações do navegador.",
    "lembretes.perm.nao_concedida": "Permissão não concedida.",
    "insights.card.sequencia": "Sequência",
    "insights.card.hoje": "Hoje",
    "insights.card.30dias": "30 dias",
    "insights.card.recorde": "Recorde",
    "insights.card.compromissos": "compromissos concluídos",
    "insights.card.taxa": "taxa de conclusão",
    "insights.card.melhor": "melhor sequência individual",
    "streak.global.0": "Hoje é um novo começo — um passo já conta.",
    "streak.global.1": "1 dia seguido. Sem pressão pra manter — só celebre.",
    "streak.global.curto": "{{n}} dias seguidos. Você tá construindo ritmo.",
    "streak.global.medio": "{{n}} dias! Isso é consistência de verdade.",
    "streak.global.longo": "{{n}} dias seguidos — impressionante, mas descanse se precisar.",
    "streak.habito.voltou": "Voltou depois de {{n}} dias — isso também conta.",
    "streak.habito.1": "1 dia — começo leve.",
    "streak.habito.recorde": "Recorde! {{n}} dias seguidos.",
    "streak.habito.normal": "{{n}} dias seguidos",
    "streak.rotulo.0": "Recomeço",
    "streak.rotulo.1": "dia seguido",
    "streak.rotulo.n": "dias seguidos",
    "diario.salvando": "Salvando…",
    "diario.salvo": "Salvo às {{hora}} · {{n}} caracteres",
    "diario.historico.meta": "{{hora}} · {{n}} caracteres · {{motivo}}",
    "diario.motivo.manual": "salvo por você",
    "diario.motivo.apagar": "antes de apagar",
    "diario.motivo.fechar": "ao sair",
    "diario.motivo.auto": "automático",
    "ajustes.sobre.versao.html": "Se a versão não mudar sozinha, toque em <strong>Buscar atualização</strong> abaixo.",
  },
  en: {
    "app.title": "Agenda — Your day",
    "header.brand": "Agenda",
    "header.day": "Your day",
    "nav.hoje": "Today",
    "nav.guia": "Guide",
    "nav.estudo": "Study",
    "nav.rotina": "Routine",
    "nav.semana": "Week",
    "nav.diario": "Journal",
    "nav.insights": "Insights",
    "nav.ajustes": "Settings",
    "nav.aria": "App sections",
    "panel.hoje": "Your day",
    "panel.guia": "Guide",
    "panel.cheguei": "What now?",
    "panel.estudo": "Study",
    "panel.rotina": "Your routine",
    "panel.semana": "Your week",
    "panel.diario": "Journal",
    "panel.insights": "Insights",
    "panel.ajustes": "Settings",
    "panel.default": "Agenda",
    "theme.aria": "Toggle theme",
    "guia.chamada.html":
      "<strong>New here?</strong> The <strong>Guide</strong> has a 5-minute walkthrough to demo the app with confidence.",
    "guia.chamada.abrir": "Open Guide",
    "guia.chamada.depois": "Later",
    "dica.inicio.html":
      "<strong>Today</strong> is your main tab: <strong>Now</strong> suggests the next step. Mark up to <strong>3 priorities</strong> with ☆.",
    "dica.entendi": "Got it",
    "hoje.manha.titulo": "Morning — 2 min",
    "hoje.manha.apoio": "What matters today? Three lines max.",
    "hoje.prioridade": "Priority {{n}}",
    "hoje.prioridade1": "Priority 1",
    "hoje.prioridade2": "Priority 2",
    "hoje.prioridade3": "Priority 3",
    "hoje.tema": "Weekly theme",
    "hoje.tema.placeholder": "E.g.: Knowledge and routine",
    "hoje.agora": "Now",
    "hoje.inbox.titulo": "Inbox — quick capture",
    "hoje.inbox.apoio": "Any thought in 10 seconds. Organize later — no pressure.",
    "hoje.inbox.placeholder": "E.g.: call the doctor, work idea...",
    "hoje.inbox.anotar": "Note",
    "hoje.inbox.vazio": "Inbox empty. When something comes up, drop it here.",
    "hoje.inbox.arquivar": "Save all and clear your head",
    "hoje.avisos.titulo": "Reminders",
    "hoje.avisos.apoio":
      "Date and time reminders — like a calendar. Turn on notifications in <strong>Settings</strong>.",
    "hoje.avisos.placeholder": "E.g.: Submit homework, doctor appointment...",
    "hoje.avisos.adicionar": "Add reminder",
    "hoje.avisos.vazio": "No reminders for today.",
    "hoje.compromissos": "Today's commitments",
    "hoje.ritmo": "Weekly rhythm",
    "hoje.revisao.titulo": "Day review — 2 min",
    "hoje.revisao.apoio": "What stuck? What's for tomorrow? No judgment.",
    "hoje.nota.titulo": "Today's notes",
    "hoje.nota.placeholder": "Free form — mood, ideas, anything to remember.",
    "agora.link.cheguei": "What now? — only 2 options",
    "agora.dica": "One step only. You don't have to do everything.",
    "agora.vazio": "Nothing pending now. Rest or check your inbox.",
    "agora.mais": "More options",
    "agora.travei": "I'm stuck",
    "agora.cronometro": "Stopwatch",
    "agora.parar": "Stop",
    "agora.travei.titulo": "Stuck? Plan B — the bare minimum",
    "agora.travei.30s": "Just 30 seconds",
    "agora.travei.ok": "OK, got it",
    "cheguei.voltar": "← Back to Guide",
    "cheguei.ola": "What now?",
    "cheguei.apoio": "No huge list — tell me what just happened and I'll give you 2 options.",
    "cheguei.apoio.madrugada": "It's late — no heavy work. What just happened?",
    "cheguei.voz": "Speak — I'll understand",
    "cheguei.ou.voz": "or choose:",
    "cheguei.ou": "or",
    "cheguei.reiniciar": "Different situation",
    "cheguei.feito.titulo": "Nice.",
    "cheguei.feito.mais": "See 2 more options",
    "cheguei.ia": "✨ adjusted by AI",
    "cheguei.gatilho.chegada": "I got home",
    "cheguei.gatilho.tarefa": "I finished a task",
    "cheguei.gatilho.acordar": "I just woke up",
    "cheguei.gatilho.pausa": "I need a break",
    "cheguei.gatilho.noite": "I'm winding down",
    "guia.hero.kicker": "App guide · v{{versao}}",
    "guia.hero.titulo": "Everything you need to show — in one place",
    "guia.hero.apoio":
      "{{faixa}} · {{hora}}. Built for ADHD: few choices, small steps, no guilt.",
    "guia.demo.iniciar": "▶ Start 5-min walkthrough",
    "guia.cheguei.btn": "What now? — 2 options",
    "guia.progresso": "Demo walkthrough",
    "guia.reset": "Reset walkthrough progress",
    "guia.mapa.titulo": "Quick map of tabs",
    "guia.mapa.apoio": "Tap to go directly. <em>What now?</em> isn't in the bar — it's here and in Today.",
    "guia.dicas.titulo": "Before showing someone",
    "guia.ia.ativa": "✨ AI active on server — Neuro, Journal and Now can use intelligence.",
    "guia.ia.local":
      "⚠️ AI offline — set GROQ_API_KEY on Vercel for Neuro, Journal and What now?",
    "guia.demo.banner": "Presentation mode — step <strong>{{atual}}</strong> of {{total}}",
    "guia.demo.proximo": "Next step →",
    "guia.demo.sair": "Exit mode",
    "guia.passo.abrir": "Open and show →",
    "guia.passo.feito": "✓ Done",
    "guia.passo.marcar": "Mark as done",
    "guia.passo.falar": "<strong>What to say:</strong> {{texto}}",
    "guia.tempo.30s": "30 s",
    "guia.tempo.1min": "1 min",
    "guia.tempo.2min": "2 min",
    "guia.rota.hoje.titulo": "Today — your hub",
    "guia.rota.hoje.falar":
      "Habits, weekly progress and the moment suggestion. Show checking a habit and the Now block.",
    "guia.rota.cheguei.titulo": "What now? — only 2 options",
    "guia.rota.cheguei.falar":
      "When your brain freezes, the app offers at most two contextual choices — no endless list.",
    "guia.rota.neuro.titulo": "Study → Neuro",
    "guia.rota.neuro.falar":
      "Neuroscience track: read, explain by voice or text, get feedback. The ADHD module stands out.",
    "guia.rota.diario.titulo": "Journal with AI",
    "guia.rota.diario.falar":
      "Daily notes stay safe. Tap Organize with AI for a gentle summary.",
    "guia.rota.insights.titulo": "Insights — gentle streaks",
    "guia.rota.insights.falar": "No guilt: streaks and patterns show real progress, not pressure.",
    "guia.ref.hoje": "Checklist, Now, inbox, reminders and day review.",
    "guia.ref.estudo": "Neuro, books, videos, English practice and pronunciation.",
    "guia.ref.rotina": "Build habits with AI or edit your full routine.",
    "guia.ref.semana": "Week view and smart plan.",
    "guia.ref.diario": "Notes by day — sacred data, with history.",
    "guia.ref.insights": "Streaks, completion rate and habit calendar.",
    "guia.ref.ajustes": "Sync, reminders, export data and app version.",
    "guia.dica.1": "Use Chrome or Safari on your phone — voice and home screen install work best.",
    "guia.dica.2": "Allow the microphone the first time (Study → Neuro → Explain by voice only).",
    "guia.dica.3": "If something looks old, hold reload to refresh the version.",
    "guia.dica.4": "The app works offline; AI (when configured) needs internet on Vercel.",
    "guia.dica.5": "To impress: start with the walkthrough below — about 5 minutes.",
    "faixa.manha": "morning",
    "faixa.tarde": "afternoon",
    "faixa.noite": "evening",
    "faixa.madrugada": "late night",
    "ajustes.idioma.titulo": "Language",
    "ajustes.idioma.apoio": "For now: Portuguese and English. The app remembers your choice.",
    "ajustes.idioma.pt": "Português",
    "ajustes.idioma.en": "English",
    "ajustes.rotina.titulo": "Your routine",
    "ajustes.rotina.apoio":
      "Tweak your times — the routine recalculates study, water and sleep automatically.",
    "ajustes.rotina.acordar": "Wake up",
    "ajustes.rotina.dormir": "Sleep",
    "ajustes.rotina.chegada": "Home arrival",
    "ajustes.rotina.tardeFim": "Hard afternoon ends",
    "ajustes.rotina.praia": "Beach work on weekends",
    "ajustes.rotina.preview": "Routine preview",
    "ajustes.rotina.botao": "Rebuild full routine",
    "ajustes.rotina.confirmar":
      "This updates {{total}} routine habits (study at {{estudo}}). Custom habits are kept. Continue?",
    "ajustes.rotina.ok": "Routine rebuilt! {{novos}} new, {{atualizados}} updated. See Today tab.",
    "ajustes.rotina.erro": "Could not rebuild the routine. Try again.",
    "ajustes.rotina.perfil": "Wakes {{acordar}}, school Mon–Fri, hard afternoon {{tardeIni}}–{{tardeFim}}. Priorities: {{prioridades}}.",
    "ajustes.sobre.titulo": "About",
    "ajustes.sobre.apoio": "Your personal agenda — commitments, notes and weekly view. Use little. Use daily.",
    "ajustes.atualizar": "Check for updates",
    "feedback.idioma": "Language changed.",
    "feedback.guia.reset": "Walkthrough progress reset.",
    "feedback.demo.fim": "Walkthrough complete! You nailed the demo.",
    "feedback.demo.passo": "Demo — {{titulo}}",
    "rotina.adicionar.titulo": "Add habit",
    "rotina.adicionar.apoio": "Tap a shortcut or type a name. Use the Today tab to check off.",
    "rotina.adicionar.placeholder": "Habit name...",
    "rotina.adicionar.btn": "Add",
    "rotina.opcoes.summary": "Time and importance (optional)",
    "rotina.atalho.agua": "💧 Water",
    "rotina.atalho.academia": "🏋️ Gym",
    "rotina.atalho.estudo": "🎧 Learn",
    "rotina.atalho.vocabulario": "🗣️ Vocabulary",
    "rotina.atalho.praticalivro": "📖 Practice",
    "rotina.atalho.meditar": "🧘 Meditate",
    "rotina.sugestao.usar": "Use suggestion",
    "rotina.importancia.1": "Essential",
    "rotina.importancia.2": "Important",
    "rotina.importancia.3": "Normal",
    "diario.titulo": "Journal",
    "diario.apoio": "Write freely. Tap Organize with AI for a gentle summary.",
    "diario.apoio.html":
      "Each day keeps one entry. It's the <strong>same text</strong> as <strong>Today → Today's notes</strong>. Auto-saves on every change — <strong>each save creates a version</strong> in <strong>History</strong>.",
    "diario.data": "Date",
    "diario.placeholder": "Write about this day…",
    "diario.hoje": "Go to today",
    "diario.ontem": "See yesterday",
    "diario.salvar": "Save entry",
    "diario.resumo.ia": "Organize with AI",
    "diario.historico": "History",
    "diario.historico.apoio": "A new version on every auto or manual save. Tap to restore.",
    "diario.historico.vazio": "No saved versions for this date yet. Write a bit — the app saves automatically.",
    "diario.busca.titulo": "Search old text",
    "diario.busca.apoio": "Searches history and the whole browser for long texts that may have gone missing.",
    "diario.busca.btn": "Search now",
    "diario.busca.vazio": "No results yet. Tap <strong>Search now</strong>.",
    "diario.entradas": "Saved entries",
    "diario.entradas.apoio": "Tap a date to open that note.",
    "diario.vazio":
      "No entries yet. Write in Today or here — they show up automatically. If yesterday's text vanished, tap <strong>See yesterday</strong> or <strong>Restore notes</strong> if shown above.",
    "semana.grafico": "Last 7 days",
    "semana.grafico.apoio": "Percentage of habits completed per day.",
    "semana.metas": "Weekly goals",
    "semana.metas.apoio": "How much is left for each weekly goal.",
    "semana.resumo": "Summary",
    "semana.resumo.titulo": "Week summary",
    "semana.resumo.apoio": "A read on your last 7-day cycle.",
    "semana.plano.ia": "Smart weekly plan",
    "insights.mes": "This month — keep the streak",
    "insights.mes.apoio": "Intensity = how much of the day's agenda you completed.",
    "sync.titulo": "Sync Mac and iPhone",
    "sync.apoio": "Same code on every device — your data stays in sync.",
    "sync.criar": "Create sync",
    "sync.codigo": "Code:",
    "sync.placeholder": "Code from your other device",
    "sync.carregando": "Loading…",
    "sync.apoio.html":
      "Create a code on this device and enter the same code on the other. Habits, journal and Neuro track stay in sync — even when switching hosts (GitHub → Vercel).",
    "sync.entrar": "Enter with code",
    "sync.copiar": "Copy code",
    "sync.desconectar": "Disconnect",
    "lembretes.titulo": "Phone reminders",
    "lembretes.apoio": "Notifications for habits and reminders — works best with the iPhone home screen app.",
    "lembretes.apoio.html":
      "Install the app on your home screen to get alerts even with the browser closed. Browser menu → <strong>Add to Home Screen</strong>.",
    "lembretes.btn": "Enable reminders",
    "vercel.titulo": "Main app (Vercel)",
    "vercel.apoio": "Recommended URL on iPhone and Mac — full app + AI + auto deploy on every git push:",
    "vercel.apoio.html":
      "Recommended URL on iPhone and Mac — full app + AI + auto deploy on every <code>git push</code>: <a href=\"https://projeto-1-criar.vercel.app\" target=\"_blank\" rel=\"noopener noreferrer\">projeto-1-criar.vercel.app</a>",
    "vercel.dica": "Use the <strong>same sync code</strong> on all devices. AI via <strong>Groq</strong> on Vercel — no local fallback.",
    "backup.titulo": "Data backup",
    "backup.apoio": "Even with sync, export once in a while. Backup is an extra safety copy.",
    "backup.exportar": "Export",
    "backup.importar": "Import",
    "hoje.nota.salvar": "Save notes",
    "migracao.github.texto": "For full AI and sync, use the Vercel version:",
    "migracao.github.html":
      "New version with AI: <a data-migracao-link-vercel href=\"https://projeto-1-criar.vercel.app\">projeto-1-criar.vercel.app</a> — use the <strong>same sync code</strong>.",
    "migracao.github.ir": "Open on Vercel",
    "migracao.host.titulo": "Restore your data",
    "migracao.host.texto": "This device doesn't have your sync code yet. Connect in Settings to bring journal and habits.",
    "migracao.host.texto.html":
      "This address is new on this device. Your <strong>journal</strong>, habits and Neuro track are safe in <strong>sync</strong> — sign in with the same code you use on your phone.",
    "migracao.host.alerta":
      "⚠️ Before writing in the journal here, connect sync so you don't overwrite the cloud with empty text.",
    "migracao.host.ajustes": "Go to Settings → Sync",
    "migracao.host.exportar": "Export backup",
    "rotina.adicionar.apoio.html": "Tap a shortcut or type a name. Use the <strong>Today</strong> tab to check off.",
    "hoje.nota.apoio.html":
      "What marked this day? History lives in the <strong>Journal</strong> tab — it's the same entry as today.",
    "neuro.titulo": "Neuro — learn by explaining",
    "neuro.fase": "Phase D",
    "neuro.trilha.apoio": "Track with {{total}} modules · read → explain (voice or text) → feedback{{ia}}. Today: {{hoje}}/{{total}}.",
    "neuro.trilha.ia": " with AI",
    "neuro.pontos": "Key points",
    "neuro.explicar.dica": "As if teaching a friend — voice or text.",
    "neuro.placeholder": "Write or use the microphone above...",
    "neuro.verificar.ia": "Check with AI ✨",
    "neuro.verificar.local": "Check my explanation",
    "neuro.proximo": "Next: {{titulo}} →",
    "neuro.timer": "10 min timer",
    "neuro.voz.completa": "🎤 Explain with voice only",
    "neuro.voz.dictado": "🎤 Add by voice",
    "neuro.voz.indisponivel": "Microphone unavailable — write below.",
    "neuro.ia.carregando": "✨ AI is reading your explanation…",
    "neuro.fb.fonte": "AI correction ✨",
    "neuro.fb.pct": "{{pct}}% of the essentials",
    "neuro.fb.acertos": "You mentioned:",
    "neuro.fb.faltou": "Still worth including:",
    "neuro.fb.pergunta": "To reflect:",
    "neuro.fb.ouvir": "🔊 Hear feedback",
    "neuro.fb.responder": "🎤 Answer question",
    "common.fechar": "Close",
    "sync.aviso.firebase.html":
      "Firebase still needs setup (it's free). Ask your assistant for steps or paste the config in <code>firebase-config.js</code>.",
    "sync.status.firebase": "Firebase not configured yet.",
    "sync.status.ativo": "Sync active on this device.",
    "sync.status.sem": "No sync. Create a code or enter an existing one.",
    "sync.status.sincronizado": "Synced just now.",
    "sync.status.falha_envio": "Failed to upload. Try again.",
    "sync.status.atualizado_nuvem": "Updated from cloud.",
    "sync.status.erro_ouvir": "Error listening to cloud.",
    "sync.status.codigo_invalido": "Invalid code. Use at least 6 characters.",
    "sync.status.codigo_nao_encontrado": "Code not found. Check it or create a new sync.",
    "sync.status.criado": "Sync created. Use this code on your other device.",
    "sync.status.conectado": "Connected. Data synced.",
    "sync.status.desconectado": "Sync turned off on this device. Local data stays here.",
    "sync.status.copiado": "Code copied. Paste it on your other device.",
    "sync.status.copia_falha": "Could not copy. Write down the code: {{codigo}}",
    "sync.status.erro_criar": "Error creating sync.",
    "sync.status.erro_conectar": "Error connecting.",
    "sync.status.firebase_lib": "Firebase library did not load.",
    "sync.status.firebase_init": "Could not start Firebase. Check your configuration.",
    "lembretes.status.indisponivel": "Notifications unavailable in this browser.",
    "lembretes.status.ativo": "Reminders on — alerts at scheduled times (best with home screen app).",
    "lembretes.status.bloqueado": "Permission blocked. Enable in browser settings.",
    "lembretes.status.off": "Reminders off.",
    "lembretes.perm.indisponivel": "This browser doesn't support notifications.",
    "lembretes.perm.ativado": "Reminders enabled.",
    "lembretes.perm.negado": "Permission denied. Enable in browser settings.",
    "lembretes.perm.nao_concedida": "Permission not granted.",
    "insights.card.sequencia": "Streak",
    "insights.card.hoje": "Today",
    "insights.card.30dias": "30 days",
    "insights.card.recorde": "Record",
    "insights.card.compromissos": "commitments done",
    "insights.card.taxa": "completion rate",
    "insights.card.melhor": "best individual streak",
    "streak.global.0": "Today is a fresh start — one step counts.",
    "streak.global.1": "1 day in a row. No pressure to keep going — just celebrate.",
    "streak.global.curto": "{{n}} days in a row. You're building rhythm.",
    "streak.global.medio": "{{n}} days! That's real consistency.",
    "streak.global.longo": "{{n}} days in a row — impressive, but rest if you need to.",
    "streak.habito.voltou": "Back after {{n}} days — that counts too.",
    "streak.habito.1": "1 day — a light start.",
    "streak.habito.recorde": "Record! {{n}} days in a row.",
    "streak.habito.normal": "{{n}} days in a row",
    "streak.rotulo.0": "Fresh start",
    "streak.rotulo.1": "day in a row",
    "streak.rotulo.n": "days in a row",
    "diario.salvando": "Saving…",
    "diario.salvo": "Saved at {{hora}} · {{n}} characters",
    "diario.historico.meta": "{{hora}} · {{n}} characters · {{motivo}}",
    "diario.motivo.manual": "saved by you",
    "diario.motivo.apagar": "before deleting",
    "diario.motivo.fechar": "on exit",
    "diario.motivo.auto": "automatic",
    "ajustes.sobre.versao.html": "If the version doesn't update on its own, tap <strong>Check for updates</strong> below.",
  },
};
