/** Dicionários PT / EN — chaves estáveis para i18n. */

export const TRADUCOES = {
  pt: {
    "app.title": "Agenda — Seu dia",
    "header.brand": "Agenda",
    "header.day": "Seu dia",
    "nav.hoje": "Hoje",
    "nav.guia": "Guia",
    "nav.estudo": "Estudo",
    "nav.rotina": "Rotina",
    "nav.semana": "Semana",
    "nav.diario": "Diário",
    "nav.insights": "Insights",
    "nav.ajustes": "Ajustes",
    "nav.aria": "Seções do app",
    "panel.hoje": "Seu dia",
    "panel.guia": "Guia",
    "panel.cheguei": "E agora?",
    "panel.estudo": "Estudo",
    "panel.rotina": "Sua rotina",
    "panel.semana": "Sua semana",
    "panel.diario": "Diário",
    "panel.insights": "Insights",
    "panel.ajustes": "Ajustes",
    "panel.default": "Agenda",
    "theme.aria": "Alternar tema",
    "guia.chamada.html":
      "<strong>Nova aqui?</strong> O <strong>Guia</strong> tem o roteiro de 5 min para mostrar o app com confiança.",
    "guia.chamada.abrir": "Abrir Guia",
    "guia.chamada.depois": "Depois",
    "dica.inicio.html":
      "<strong>Hoje</strong> é sua aba principal: <strong>Agora</strong> diz o próximo passo. Marque até <strong>3 prioridades</strong> com ☆.",
    "dica.entendi": "Entendi",
    "hoje.manha.titulo": "Manhã — 2 min",
    "hoje.manha.apoio": "O que importa hoje? Três linhas no máximo.",
    "hoje.prioridade": "Prioridade {{n}}",
    "hoje.prioridade1": "Prioridade 1",
    "hoje.prioridade2": "Prioridade 2",
    "hoje.prioridade3": "Prioridade 3",
    "hoje.tema": "Tema da semana",
    "hoje.tema.placeholder": "Ex.: Conhecimento e rotina",
    "hoje.agora": "Agora",
    "hoje.inbox.titulo": "Inbox — captura rápida",
    "hoje.inbox.apoio": "Qualquer pensamento em 10 segundos. Organize depois — sem pressão.",
    "hoje.inbox.placeholder": "Ex.: ligar pro médico, ideia do trabalho...",
    "hoje.inbox.anotar": "Anotar",
    "hoje.inbox.vazio": "Nada na inbox. Quando surgir algo, jogue aqui.",
    "hoje.inbox.arquivar": "Guardar tudo e limpar a cabeça",
    "hoje.avisos.titulo": "Avisos",
    "hoje.avisos.apoio":
      "Lembretes com data e hora — como no calendário. Ative notificações em <strong>Ajustes</strong>.",
    "hoje.avisos.placeholder": "Ex.: Entregar trabalho, consulta médica...",
    "hoje.avisos.adicionar": "Adicionar aviso",
    "hoje.avisos.vazio": "Nenhum aviso para hoje.",
    "hoje.compromissos": "Compromissos de hoje",
    "hoje.ritmo": "Ritmo da semana",
    "hoje.revisao.titulo": "Revisão do dia — 2 min",
    "hoje.revisao.apoio": "O que ficou? O que amanhã? Sem julgamento.",
    "hoje.nota.titulo": "Anotações do dia",
    "hoje.nota.placeholder": "Livre — humor, ideias, o que quiser lembrar.",
    "agora.link.cheguei": "E agora? — só 2 opções",
    "agora.dica": "Um passo só. Sem precisar fazer tudo.",
    "agora.vazio": "Nada pendente agora. Descanse ou revise a inbox.",
    "agora.mais": "Mais opções",
    "agora.travei": "Travei",
    "agora.cronometro": "Cronômetro",
    "agora.parar": "Parar",
    "agora.travei.titulo": "Travou? Plano B — só o mínimo",
    "agora.travei.30s": "Só 30 segundos",
    "agora.travei.ok": "Ok, entendi",
    "cheguei.voltar": "← Voltar ao Guia",
    "cheguei.ola": "E agora?",
    "cheguei.apoio": "Sem lista enorme — diga o que acabou de acontecer e eu monto 2 opções.",
    "cheguei.apoio.madrugada": "É madrugada — nada de trabalho pesado. Diga o que acabou de acontecer:",
    "cheguei.voz": "Falar — eu entendo",
    "cheguei.ou.voz": "ou escolha:",
    "cheguei.ou": "ou",
    "cheguei.reiniciar": "Outra situação",
    "cheguei.feito.titulo": "Boa.",
    "cheguei.feito.mais": "Ver mais 2 opções",
    "cheguei.ia": "✨ ajustado pela IA",
    "cheguei.gatilho.chegada": "Cheguei em casa",
    "cheguei.gatilho.tarefa": "Completei uma tarefa",
    "cheguei.gatilho.acordar": "Acabei de acordar",
    "cheguei.gatilho.pausa": "Preciso de uma pausa",
    "cheguei.gatilho.noite": "Vou desacelerar",
    "guia.hero.kicker": "Guia do app · v{{versao}}",
    "guia.hero.titulo": "Tudo que você precisa mostrar — em um lugar só",
    "guia.hero.apoio":
      "{{faixa}} · {{hora}}. App feito para TDAH: poucas escolhas, passos pequenos, sem culpa.",
    "guia.demo.iniciar": "▶ Iniciar roteiro de 5 min",
    "guia.cheguei.btn": "E agora? — 2 opções",
    "guia.progresso": "Roteiro de demonstração",
    "guia.reset": "Zerar progresso do roteiro",
    "guia.mapa.titulo": "Mapa rápido das abas",
    "guia.mapa.apoio": "Toque para ir direto. <em>E agora?</em> não está na barra — fica aqui e em Hoje.",
    "guia.dicas.titulo": "Antes de mostrar para alguém",
    "guia.ia.ativa": "✨ IA ativa no servidor — Neuro, Diário e Agora podem usar inteligência.",
    "guia.ia.local":
      "ℹ️ IA local ativa — funciona sem chave; configure GROQ no Vercel para IA completa.",
    "guia.demo.banner": "Modo apresentação — passo <strong>{{atual}}</strong> de {{total}}",
    "guia.demo.proximo": "Próximo passo →",
    "guia.demo.sair": "Sair do modo",
    "guia.passo.abrir": "Abrir e mostrar →",
    "guia.passo.feito": "✓ Feito",
    "guia.passo.marcar": "Marcar como feito",
    "guia.passo.falar": "<strong>O que dizer:</strong> {{texto}}",
    "guia.tempo.30s": "30 s",
    "guia.tempo.1min": "1 min",
    "guia.tempo.2min": "2 min",
    "guia.rota.hoje.titulo": "Hoje — centro do dia",
    "guia.rota.hoje.falar":
      "Hábitos, progresso da semana e a sugestão do momento. Mostre marcar um hábito e o bloco Agora.",
    "guia.rota.cheguei.titulo": "E agora? — só 2 opções",
    "guia.rota.cheguei.falar":
      "Quando a cabeça trava, o app oferece no máximo duas escolhas contextuais — sem lista infinita.",
    "guia.rota.neuro.titulo": "Estudo → Neuro",
    "guia.rota.neuro.falar":
      "Trilha de neurociência: ler, explicar com voz ou texto e receber feedback. Módulo TDAH impressiona.",
    "guia.rota.diario.titulo": "Diário com IA",
    "guia.rota.diario.falar":
      "Anotações do dia ficam seguras. Toque em Organizar com IA para um resumo gentil.",
    "guia.rota.insights.titulo": "Insights — streak gentil",
    "guia.rota.insights.falar": "Sem culpa: sequências e padrões mostram progresso real, não cobrança.",
    "guia.ref.hoje": "Checklist, Agora, inbox, avisos e revisão do dia.",
    "guia.ref.estudo": "Neuro, livros, vídeos, prática de inglês e pronúncia.",
    "guia.ref.rotina": "Montar hábitos com IA ou editar a rotina completa.",
    "guia.ref.semana": "Visão da semana e plano inteligente.",
    "guia.ref.diario": "Notas por dia — dados sagrados, com histórico.",
    "guia.ref.insights": "Sequências, taxa de conclusão e calendário de hábitos.",
    "guia.ref.ajustes": "Sync, lembretes, exportar dados e versão do app.",
    "guia.dica.1": "Use Chrome ou Safari no celular — voz e instalação na tela inicial funcionam melhor.",
    "guia.dica.2": "Permita o microfone na primeira vez (Estudo → Neuro → Explicar só com voz).",
    "guia.dica.3": "Se algo parecer antigo, segure o botão de recarregar para atualizar a versão.",
    "guia.dica.4": "O app funciona offline; IA (quando configurada) precisa de internet no Vercel.",
    "guia.dica.5": "Para impressionar: comece pelo roteiro abaixo — leva cerca de 5 minutos.",
    "faixa.manha": "manhã",
    "faixa.tarde": "tarde",
    "faixa.noite": "noite",
    "faixa.madrugada": "madrugada",
    "ajustes.idioma.titulo": "Idioma",
    "ajustes.idioma.apoio": "Por enquanto: português e inglês. O app lembra sua escolha.",
    "ajustes.idioma.pt": "Português",
    "ajustes.idioma.en": "English",
    "ajustes.sobre.titulo": "Sobre",
    "ajustes.sobre.apoio": "Sua agenda pessoal — compromissos, anotações e visão da semana. Use pouco. Use todo dia.",
    "ajustes.atualizar": "Buscar atualização",
    "feedback.idioma": "Idioma alterado.",
    "feedback.guia.reset": "Progresso do roteiro zerado.",
    "feedback.demo.fim": "Roteiro completo! Você arrasou na demonstração.",
    "feedback.demo.passo": "Demonstração — {{titulo}}",
  },
  en: {
    "app.title": "Agenda — Your day",
    "header.brand": "Agenda",
    "header.day": "Your day",
    "nav.hoje": "Today",
    "nav.guia": "Guide",
    "nav.estudo": "Study",
    "nav.rotina": "Routine",
    "nav.semana": "Week",
    "nav.diario": "Journal",
    "nav.insights": "Insights",
    "nav.ajustes": "Settings",
    "nav.aria": "App sections",
    "panel.hoje": "Your day",
    "panel.guia": "Guide",
    "panel.cheguei": "What now?",
    "panel.estudo": "Study",
    "panel.rotina": "Your routine",
    "panel.semana": "Your week",
    "panel.diario": "Journal",
    "panel.insights": "Insights",
    "panel.ajustes": "Settings",
    "panel.default": "Agenda",
    "theme.aria": "Toggle theme",
    "guia.chamada.html":
      "<strong>New here?</strong> The <strong>Guide</strong> has a 5-minute walkthrough to demo the app with confidence.",
    "guia.chamada.abrir": "Open Guide",
    "guia.chamada.depois": "Later",
    "dica.inicio.html":
      "<strong>Today</strong> is your main tab: <strong>Now</strong> suggests the next step. Mark up to <strong>3 priorities</strong> with ☆.",
    "dica.entendi": "Got it",
    "hoje.manha.titulo": "Morning — 2 min",
    "hoje.manha.apoio": "What matters today? Three lines max.",
    "hoje.prioridade": "Priority {{n}}",
    "hoje.prioridade1": "Priority 1",
    "hoje.prioridade2": "Priority 2",
    "hoje.prioridade3": "Priority 3",
    "hoje.tema": "Weekly theme",
    "hoje.tema.placeholder": "E.g.: Knowledge and routine",
    "hoje.agora": "Now",
    "hoje.inbox.titulo": "Inbox — quick capture",
    "hoje.inbox.apoio": "Any thought in 10 seconds. Organize later — no pressure.",
    "hoje.inbox.placeholder": "E.g.: call the doctor, work idea...",
    "hoje.inbox.anotar": "Note",
    "hoje.inbox.vazio": "Inbox empty. When something comes up, drop it here.",
    "hoje.inbox.arquivar": "Save all and clear your head",
    "hoje.avisos.titulo": "Reminders",
    "hoje.avisos.apoio":
      "Date and time reminders — like a calendar. Turn on notifications in <strong>Settings</strong>.",
    "hoje.avisos.placeholder": "E.g.: Submit homework, doctor appointment...",
    "hoje.avisos.adicionar": "Add reminder",
    "hoje.avisos.vazio": "No reminders for today.",
    "hoje.compromissos": "Today's commitments",
    "hoje.ritmo": "Weekly rhythm",
    "hoje.revisao.titulo": "Day review — 2 min",
    "hoje.revisao.apoio": "What stuck? What's for tomorrow? No judgment.",
    "hoje.nota.titulo": "Today's notes",
    "hoje.nota.placeholder": "Free form — mood, ideas, anything to remember.",
    "agora.link.cheguei": "What now? — only 2 options",
    "agora.dica": "One step only. You don't have to do everything.",
    "agora.vazio": "Nothing pending now. Rest or check your inbox.",
    "agora.mais": "More options",
    "agora.travei": "I'm stuck",
    "agora.cronometro": "Stopwatch",
    "agora.parar": "Stop",
    "agora.travei.titulo": "Stuck? Plan B — the bare minimum",
    "agora.travei.30s": "Just 30 seconds",
    "agora.travei.ok": "OK, got it",
    "cheguei.voltar": "← Back to Guide",
    "cheguei.ola": "What now?",
    "cheguei.apoio": "No huge list — tell me what just happened and I'll give you 2 options.",
    "cheguei.apoio.madrugada": "It's late — no heavy work. What just happened?",
    "cheguei.voz": "Speak — I'll understand",
    "cheguei.ou.voz": "or choose:",
    "cheguei.ou": "or",
    "cheguei.reiniciar": "Different situation",
    "cheguei.feito.titulo": "Nice.",
    "cheguei.feito.mais": "See 2 more options",
    "cheguei.ia": "✨ adjusted by AI",
    "cheguei.gatilho.chegada": "I got home",
    "cheguei.gatilho.tarefa": "I finished a task",
    "cheguei.gatilho.acordar": "I just woke up",
    "cheguei.gatilho.pausa": "I need a break",
    "cheguei.gatilho.noite": "I'm winding down",
    "guia.hero.kicker": "App guide · v{{versao}}",
    "guia.hero.titulo": "Everything you need to show — in one place",
    "guia.hero.apoio":
      "{{faixa}} · {{hora}}. Built for ADHD: few choices, small steps, no guilt.",
    "guia.demo.iniciar": "▶ Start 5-min walkthrough",
    "guia.cheguei.btn": "What now? — 2 options",
    "guia.progresso": "Demo walkthrough",
    "guia.reset": "Reset walkthrough progress",
    "guia.mapa.titulo": "Quick map of tabs",
    "guia.mapa.apoio": "Tap to go directly. <em>What now?</em> isn't in the bar — it's here and in Today.",
    "guia.dicas.titulo": "Before showing someone",
    "guia.ia.ativa": "✨ AI active on server — Neuro, Journal and Now can use intelligence.",
    "guia.ia.local":
      "ℹ️ Local mode active — works without a key; set GROQ on Vercel for full AI.",
    "guia.demo.banner": "Presentation mode — step <strong>{{atual}}</strong> of {{total}}",
    "guia.demo.proximo": "Next step →",
    "guia.demo.sair": "Exit mode",
    "guia.passo.abrir": "Open and show →",
    "guia.passo.feito": "✓ Done",
    "guia.passo.marcar": "Mark as done",
    "guia.passo.falar": "<strong>What to say:</strong> {{texto}}",
    "guia.tempo.30s": "30 s",
    "guia.tempo.1min": "1 min",
    "guia.tempo.2min": "2 min",
    "guia.rota.hoje.titulo": "Today — your hub",
    "guia.rota.hoje.falar":
      "Habits, weekly progress and the moment suggestion. Show checking a habit and the Now block.",
    "guia.rota.cheguei.titulo": "What now? — only 2 options",
    "guia.rota.cheguei.falar":
      "When your brain freezes, the app offers at most two contextual choices — no endless list.",
    "guia.rota.neuro.titulo": "Study → Neuro",
    "guia.rota.neuro.falar":
      "Neuroscience track: read, explain by voice or text, get feedback. The ADHD module stands out.",
    "guia.rota.diario.titulo": "Journal with AI",
    "guia.rota.diario.falar":
      "Daily notes stay safe. Tap Organize with AI for a gentle summary.",
    "guia.rota.insights.titulo": "Insights — gentle streaks",
    "guia.rota.insights.falar": "No guilt: streaks and patterns show real progress, not pressure.",
    "guia.ref.hoje": "Checklist, Now, inbox, reminders and day review.",
    "guia.ref.estudo": "Neuro, books, videos, English practice and pronunciation.",
    "guia.ref.rotina": "Build habits with AI or edit your full routine.",
    "guia.ref.semana": "Week view and smart plan.",
    "guia.ref.diario": "Notes by day — sacred data, with history.",
    "guia.ref.insights": "Streaks, completion rate and habit calendar.",
    "guia.ref.ajustes": "Sync, reminders, export data and app version.",
    "guia.dica.1": "Use Chrome or Safari on your phone — voice and home screen install work best.",
    "guia.dica.2": "Allow the microphone the first time (Study → Neuro → Explain by voice only).",
    "guia.dica.3": "If something looks old, hold reload to refresh the version.",
    "guia.dica.4": "The app works offline; AI (when configured) needs internet on Vercel.",
    "guia.dica.5": "To impress: start with the walkthrough below — about 5 minutes.",
    "faixa.manha": "morning",
    "faixa.tarde": "afternoon",
    "faixa.noite": "evening",
    "faixa.madrugada": "late night",
    "ajustes.idioma.titulo": "Language",
    "ajustes.idioma.apoio": "For now: Portuguese and English. The app remembers your choice.",
    "ajustes.idioma.pt": "Português",
    "ajustes.idioma.en": "English",
    "ajustes.sobre.titulo": "About",
    "ajustes.sobre.apoio": "Your personal agenda — commitments, notes and weekly view. Use little. Use daily.",
    "ajustes.atualizar": "Check for updates",
    "feedback.idioma": "Language changed.",
    "feedback.guia.reset": "Walkthrough progress reset.",
    "feedback.demo.fim": "Walkthrough complete! You nailed the demo.",
    "feedback.demo.passo": "Demo — {{titulo}}",
  },
};
